"use client";

import React, { createContext, useContext, useState, useCallback } from 'react';

export type Language = 'en' | 'hi' | 'te';

const translations: Record<Language, Record<string, string>> = {
  en: {
    welcome_back: 'Welcome back',
    hi: 'Hi',
    dashboard: 'Dashboard',
    upload: 'Upload',
    activity: 'Activity',
    profile: 'Profile',
    snag_list: 'Snag List',
    user_mgmt: 'User Mgmt',
    billing: 'Plan/Upgrade',
    projects: 'Projects',
    documents: 'Documents',
    photos: 'Photos',
    sign_in: 'Sign In',
    sign_up: 'Sign Up',
    sign_out: 'Sign Out',
    settings: 'Settings',
    analytics: 'Analytics',
    notifications_label: 'Notifications',
    chats: 'Chats',
    teams: 'Teams',
    org_users: 'Org Users',
    all_projects: 'All Projects',
    organization_projects: 'Organization Projects',
    all_organizations: 'All Organizations',
    create_project: 'Create Project',
    search: 'Search',
    notifications: 'Notifications',
    help_support: 'Help & Support',
    feedback: 'Feedback',
    your_projects: 'Your Projects',
    total_projects: 'Total Projects',
    manage_projects: 'Manage all your company projects',
    assigned_projects: 'View and contribute to your assigned projects',
    shared_projects: 'Access your shared project files',
    no_projects: 'No projects available',
    language: 'Language',
    english: 'English',
    hindi: 'Hindi',
    telugu: 'Telugu',
    choose_plan: 'Choose Plan',
    recommended: 'Recommended',
    standard: 'Standard',
    intermediate: 'Intermediate',
    pro: 'Pro',
    project_overview: 'Project Overview',
    back_to_projects: 'Back to Projects',
    daily_reports: 'Daily Reports',
    weekly_reports: 'Weekly Reports',
    manuals: 'Checklists',
    project_not_found: 'Project not found.',
    back_to_dashboard: 'Back to Dashboard',
    name_update_success: 'Name updated successfully',
    name_update_error: 'Failed to update name',
    company_settings: 'Company Settings',
    company_name_label: 'Company Name',
    company_name_placeholder: 'Enter company name',
    company_name_success: 'Company name updated',
    company_name_error: 'Failed to update company name',
    company_logo_success: 'Company logo updated',
    company_logo_error: 'Failed to upload company logo',
    tap_change_logo: 'Tap to change logo',
    change_password: 'Change Password',
    current_password: 'Current Password',
    new_password: 'New Password',
    confirm_password: 'Confirm New Password',
    password_mismatch: 'Passwords do not match',
    password_success: 'Password updated successfully',
    password_error: 'Failed to update password',
    update_password: 'Update Password',
    trash_management: 'Trash Management',
    trash_management_subtitle: 'Recover or purge deleted projects',
    crop_photo_title: 'Crop Profile Photo',
    save_photo: 'Save Photo',
    profile_pic_success: 'Profile picture updated successfully',
    profile_pic_error: 'Failed to upload profile picture',
    cancel: 'Cancel',
    save: 'Save',
    trash_title: 'Trash',
    trash_subtitle: 'Manage and restore deleted items',
    loading_trash: 'Loading trash...',
    trash_empty: 'Trash is Empty',
    trash_empty_desc: 'Deleted items will appear here for 30 days before being permanently removed.',
    day_left: 'DAY LEFT',
    days_left: 'DAYS LEFT',
    no_description: 'No description available',
    deleted_at: 'Deleted',
    restore: 'Restore',
    delete_forever: 'Delete Forever',
    restore_success: 'Item restored successfully',
    restore_error: 'Failed to restore item',
    permanent_delete_success: 'Item permanently deleted',
    permanent_delete_error: 'Failed to delete item',
    load_trash_error: 'Failed to load trash',
    permanent_delete_confirm: 'Are you sure? This will permanently delete this item. This cannot be undone.',
    no_permission: 'You do not have permission to view this page.',
    load_users_error: 'Failed to load users',
    invalid_email: 'Please enter a valid email',
    select_project_role: 'Please select a project for this role',
    invite_success: 'Invitation sent successfully',
    invite_error: 'Failed to send invitation',
    remove_access_success: 'Project access removed successfully',
    remove_access_error: 'Failed to remove project access',
    link_copied: 'link copied to clipboard',
    user_mgmt_subtitle: 'Manage organization members and roles.',
    add_member: 'Add Member',
    email_address: 'Email Address',
    role: 'Role',
    assign_project: 'Assign Project',
    choose_project: 'Choose Project',
    no_projects_found: 'No projects found',
    invite: 'Invite',
    project_access_links: 'Project Access Links',
    project_access_links_subtitle: 'Generate direct login links for internal contributors and external clients.',
    select_project_placeholder: 'Select a Project',
    contributor_access: 'Contributor Access',
    client_access: 'Client Access',
    copy_link: 'Copy Link',
    copied: 'Copied',
    no_project_selected: 'No Project Selected',
    no_project_selected_subtitle: 'Please select a project from the dropdown above to generate direct access links for contributors and clients.',
    member: 'Member',
    status: 'Status',
    joined: 'Joined',
    actions: 'Actions',
    invited_user: 'Invited User',
    no_contact_info: 'No contact info',
    all_projects_label: '(All Projects)',
    no_projects_assigned: 'No projects assigned',
    verified: 'Verified',
    pending: 'Pending',
    no_users_found: 'No users found in your organization.',
    remove_access_title: 'Remove Project Access?',
    remove_access_confirm: 'Are you sure you want to remove {name} from their project access? The user account will stay in the organization.',
    remove_access_button: 'Remove Access',
    blocked_users: 'Blocked Users',
    active_members: 'Active Members',
    unblock: 'Unblock',
    just_delete: 'Just Delete',
    block_and_delete: 'Block & Delete',
    unblock_success: 'User unblocked successfully',
    unblock_error: 'Failed to unblock user',
    admin: 'Admin',
    contributor: 'Contributor',
    client: 'Client',
    // Billing
    billing_subtitle: 'Choose the plan that fits your team',
    monthly: 'Monthly',
    annual: 'Annual',
    save_35: 'Save 35%',
    plans_tab: 'Plans',
    usage_tab: 'Usage',
    history_tab: 'History',
    most_popular: 'Most Popular',
    billed_annually: 'Billed annually',
    incl_gst: '(Incl. 18% GST)',
    processing: 'Processing...',
    current_plan: 'Current Plan',
    resource_consumption: 'Resource Consumption',
    resource_consumption_subtitle: 'Detailed breakdown of your organization\'s resource usage',
    plan_validity: 'Plan Validity',
    active_projects: 'Active Projects',
    cloud_storage: 'Cloud Storage',
    team_members: 'Team Members',
    clients: 'Clients',
    snags: 'Snags',
    rfis: 'RFIs',
    active_status: 'Active',
    no_payment_history: 'No payment history found.',
    invoice: 'Invoice',
    cycle: 'Cycle',
    amount: 'Amount',
    date: 'Date',
    action: 'Action',
    limit: 'Limit',
    payment_success: 'Payment successful! Your plan has been upgraded.',
    payment_failed: 'Payment failed',
    payment_error: 'Something went wrong with the payment.',
    payment_sdk_error: 'Razorpay SDK failed to load. Please check your internet connection.',
    payment_verification_failed: 'Payment verification failed. Please contact support.',
    price_custom: 'Custom',
    // Chats
    access_denied: 'Access Denied',
    superadmin_chat_no_access: 'Superadmins do not have access to the chat feature.',
    loading_chats: 'Loading chats...',
    search_chats: 'Search chats...',
    no_chats_found: 'No chats found',
    chat_fallback: 'Chat',
    more_projects: '+{count} more',
    user_is_typing: '{name} is typing...',
    photo: 'Photo',
    file: 'File',
    group_chat: 'Group Chat',
    direct_message: 'Direct Message',
    loading_messages: 'Loading messages...',
    online: 'Online',
    offline: 'Offline',
    members_count: '{count} members',
    user_fallback: 'User',
    voice_note: 'Voice Note',
    photo_message: 'Photo',
    file_message: 'File',
    message_fallback: 'Message',
    replied_to_message: 'Replied to message',
    message_placeholder: 'Message...',
    new_group: 'New Group',
    new_direct_chat: 'New Direct Chat',
    search_people: 'Search people...',
    group_name_placeholder: 'Group Name',
    users_selected: '{count} selected',
    create_group_btn: 'Create Group ({count})',
    create_chat_btn: 'Create Chat',
    enter_group_name: 'Please enter a group name',
    failed_create_chat: 'Failed to create chat',
    all_actions: 'All Actions',
    snags_label: 'Snags',
    rfi_label: 'RFI',
    members_label: 'Members',
    back_to_unread: 'Back to unread',
    history: 'History',
    notifications_subtitle: 'Stay updated with project changes',
    mark_all_read: 'Mark all as read',
    all_users: 'All Users',
    no_notifications_48h: 'No notifications in the last 48 hours',
    no_new_notifications: 'No new notifications',
    all_caught_up: 'You\'re all caught up!',
    activity_subtitle: 'Updates from your projects',
    no_recent_activity: 'No recent activity',
    team_mgmt_hub: 'Team Management Hub',
    filter_access_control: 'Filter & Access Control',
    project_access: 'Project Access',
    team_role: 'Team Role',
    all_roles: 'All Roles',
    reset: 'Reset',
    copy_contributor_link: 'Copy Contributor Link',
    copy_client_link: 'Copy Client Link',
    no_users_filter: 'No users found matching your filters.',
    excellent: 'Excellent',
    moderate: 'Moderate',
    attention_needed: 'Attention Needed',
    access_restricted_admins: 'Access restricted to admins.',
    go_back: 'Go Back',
    admin_analytics: 'Admin Analytics',
    analytics_subtitle: 'Company-wide project intelligence',
    tasks_pending: 'Tasks Pending',
    tasks_overdue: 'Tasks Overdue',
    delayed_projects: 'Delayed Projects',
    avg_completion: 'Avg completion',
    project_status: 'Project Status',
    task_completion_trend: 'Task Completion Trend',
    completed_label: 'Completed',
    created_label: 'Created',
    communication_activity: 'Communication Activity',
    messages_week: 'Messages this week',
    project_pulse_score: 'Project Pulse Score',
    pulse: 'Pulse',
    progress: 'Progress',
    snags_pt: 'Snags (P/T)',
    rfis_pt: 'RFIs (P/T)',
    risk: 'Risk',
    team_leaderboard: 'Team Leaderboard',
    tasks_count: '{count} tasks',
    avg_label: 'Avg:',
    live_activity: 'Live Activity',
    critical_issue_summary: 'Critical Issue Summary',
    open_snags: 'Open Snags',
    overdue_items: 'Overdue Items',
    active_rfis: 'Active RFIs',
    file_uploads_week: 'File Uploads This Week',
    sort_by: 'Sort by:',
    sort_projects_by: 'Sort Projects By',
    name_label: 'Name',
    newest: 'Newest',
    oldest: 'Oldest',
    create_new_project: 'Create New Project',
    project_name_max: 'Project Name (max 25)',
    company_client_max: 'Company Name/Client Name (max 50)',
    enter_company_client: 'Enter Company/Client Name',
    start_date: 'Start Date',
    end_date: 'End Date',
    no_company_client: 'No Company/Client Name',
    contributor_label: 'Contributor:',
    client_label: 'Client:',
    copied_to_clipboard: 'Copied to clipboard',
    org_logo_updated: 'Organization logo updated',
    logo_upload_failed: 'Logo upload failed',
    project_limit_reached: 'Limit Reached: You have reached your project limit. Please upgrade your plan to create more projects.',
    upgrade_label: 'Upgrade',
    project_created_success: 'Project created successfully',
    project_create_failed: 'Failed to create project',
    login_to_view_dashboard: 'Please log in to view the dashboard.',
    logo_placeholder: 'Logo',
    crop_logo: 'Crop Logo',
    upload_logo_btn: 'Upload Logo',
    no_logo: 'No Logo',
    org_logo_title: 'Organization Logo',
    logo_represents: 'This logo represents {name}.',
    change_logo: 'Change Logo',
    loading_overview: 'Loading project overview...',
    failed_load_members: 'Failed to load members',
    project_access_removed: 'Project access removed',
    failed_remove_access: 'Failed to remove project access',
    export_completed: 'Export completed in {count}s!',
    export_failed: 'Export failed: {error}',
    starting_export: 'Starting export process...',
    failed_trigger_export: 'Failed to trigger export',
    failed_share_link: 'Failed to generate share link',
    client_project_code: 'Client Project Code',
    active_label: 'active',
    reports_label: 'Reports',
    files_label: 'Files',
    view_reports: 'View reports',
    open_issues: 'Open issues',
    access_codes: 'Access Codes',
    contributor_code_label: 'Contributor Code',
    client_list_label: 'Client List',
    code_restricted: 'Code Restricted',
    client_code_label: 'Client Code',
    final_handover_report: 'Final Handover Report',
    exporting_label: 'Exporting...',
    time_left: '{time} left',
    report_ready: 'Report Ready',
    generated_label: 'Generated',
    download_label: 'Download',
    generate_new_report: 'Generate New Report',
    export_final_handover: 'Export Final Handover Report',
    no_active_members: 'No active {role}s found',
    primary_label: '(Primary)',
    edit_project: 'Edit Project',
    save_changes: 'Save Changes',
    project_updated_success: 'Project updated successfully',
    project_update_failed: 'Failed to update project',
    confirm_delete_project: 'Are you sure you want to delete this project? It will be moved to the Trash and can be recovered later from your Profile settings for 30 days.',
    project_moved_trash: 'Project moved to Trash',
    delete_project_failed: 'Failed to delete project. Please try again.',
    deleting_project: 'Deleting Project',
    wait_cleaning_assets: 'Please wait while we clean up all assets...',
    doc_marked_visible: 'Document marked Visible for clients',
    doc_marked_hidden: 'Document marked Hidden for clients',
    failed_toggle_visibility: 'Failed to toggle visibility',
    doc_marked_dnf: "Document marked as 'Do Not Follow'",
    doc_unmarked_dnf: "Document unmarked as 'Do Not Follow'",
    failed_toggle_dnf: 'Failed to toggle Do Not Follow',
    doc_marked_ofr: "Document marked as 'Only for Reference'",
    doc_unmarked_ofr: "Document unmarked as 'Only for Reference'",
    failed_toggle_ofr: 'Failed to toggle Only for Reference',
    folder_marked_visible: 'Folder marked Visible for clients',
    folder_marked_hidden: 'Folder marked Hidden for clients',
    archive_confirm_msg: 'Are you sure you want to archive this document? It will be moved to the Archive folder and set to "Do Not Follow".',
    doc_archived: 'Document archived',
    failed_archive_doc: 'Failed to archive document',
    archive_name_reserved: "The name 'Archive' is reserved for system use",
    folder_created_msg: 'Folder "{name}" created',
    create_folder_title: 'Create New Folder',
    folder_name_label: 'Folder name for {type}',
    folder_name_placeholder: 'Enter folder name',
    create_folder_btn: 'Create Folder',
    failed_create_folder: 'Failed to create folder',
    folder_renamed_msg: 'Folder renamed to "{name}"',
    failed_rename_folder: 'Failed to rename folder',
    file_renamed_msg: 'File renamed to "{name}"',
    failed_rename_file: 'Failed to rename file',
    confirm_delete_folder: 'Move folder "{name}" to Trash? It can be recovered later from your Profile settings for 30 days.',
    folder_deleted_msg: 'Folder "{name}" deleted',
    failed_delete_folder: 'Failed to delete folder',
    folder_already_empty: 'Folder is already empty',
    visibility_updated_msg: 'Visibility updated for {count} items',
    dnf_updated_msg: "'Do Not Follow' updated for {count} files",
    select_file_share: 'Select at least one file to share',
    upload_file_btn: 'Upload File',
    new_folder_btn: 'New Folder',
    select_btn: 'Select',
    grid_view_tip: 'Grid view',
    list_view_tip: 'List view',
    sort_by_label: 'Sort by:',
    sort_docs_title: 'Sort Docs By',
    date_label: 'Date Modified',
    size_label: 'Size',
    files_folders_tab: 'Files & Folders',
    linked_rfi_tab: 'Linked RFIs',
    linked_rfi_and_snag_tab: 'Linked RFIs & Snags',
    move_folder_tip: 'Move folder',
    rename_folder_tip: 'Rename folder',
    files_count_label: '{count} files',
    folder_count_label: '{count} folder',
    folders_count_label: '{count} folders',
    share_link_tip: 'Share via link',
    rename_file_tip: 'Rename file',
    toggle_visibility_tip: 'Toggle Visibility',
    toggle_dnf_tip: 'Toggle Do Not Follow',
    move_file_tip: 'Move file',
    archive_file_tip: 'Archive file',
    dnf_tag: 'DNF',
    do_not_follow_tag: 'DO NOT FOLLOW',
    toggle_ofr_tip: 'Toggle Only for Reference',
    ofr_tag: 'OFR',
    only_for_reference_tag: 'ONLY FOR REFERENCE',
    toggle_client_vis_tip: 'Toggle client visibility',
    no_docs_yet: 'No folders or documents yet',
    items_selected: '{count} selected',
    share_btn: 'Share',
    move_btn: 'Move',
    show_btn: 'Show',
    hide_btn: 'Hide',
    regular_btn: 'Regular',
    clear_selection_tip: 'Clear selection',
    folder_deleted_move_msg: 'Folder "{name}" deleted after moving contents',
    failed_delete_empty_folder: 'Contents moved, but failed to delete empty folder',
    folder_not_empty_title: 'Folder Not Empty',
    folder_not_empty_desc: 'The folder {name} contains files or subfolders. How would you like to proceed?',
    delete_everything_btn: 'Delete Everything',
    delete_everything_desc: 'Permanently remove folder and all its contents',
    move_contents_first_btn: 'Move Contents First',
    move_contents_first_desc: 'Select another path for the items inside',
    photo_marked_visible: 'Photo marked Visible for clients',
    photo_marked_hidden: 'Photo marked Hidden for clients',
    photo_marked_dnf: "Photo marked as 'Do Not Follow'",
    photo_unmarked_dnf: "Photo unmarked as 'Do Not Follow'",
    confirm_delete_photo: 'Move this photo to Trash? It can be recovered later from your Profile settings for 30 days.',
    photo_deleted_msg: 'Photo deleted',
    failed_delete_photo: 'Failed to delete photo',
    select_photo_share: 'Select at least one photo to share',
    upload_photo_btn: 'Upload Photo',
    sort_photos_title: 'Sort Photos By',
    photos_folders_tab: 'Photos & Folders',
    delete_folder_tip: 'Delete folder',
    photos_count_label: '{count} photos',
    delete_photo_tip: 'Delete photo',
    no_photos_yet: 'No folders or photos yet',
    daily_label: 'Daily',
    weekly_label: 'Weekly',
    monthly_label: 'Monthly',
    daily_report: 'Daily Report',
    weekly_report: 'Weekly Report',
    monthly_report: 'Monthly Report',
    generating_label: 'Generating...',
    generate_report_btn: 'Generate {type} Report',
    report_period_to: 'to',
    download_pdf_tip: 'Download PDF',
    no_detail_records: 'No detail records for this period',
    docs_uploaded_title: 'Documents Uploaded',
    photos_uploaded_title: 'Photos Uploaded',
    uploaded_by_in: '(by {user} in {folder})',
    photos_by_in: '{count} photos by {user} in {folder}',
    no_reports_found: 'No {type} reports found',
    generate_to_start: 'Generate one to get started',
    export_options_title: 'Export Options',
    export_options_subtitle: 'Select sections to include in your report',
    waiting_clearance: 'Waiting for Clearance',
    open_status: 'OPEN',
    completed_status: 'Completed',
    resolved_status: 'RESOLVED',
    no_action_required: 'No Action Required',
    overdue_status: 'OVERDUE',
    project_snags_title: 'Project Snags',
    add_snag_btn: 'Add Snag',
    status_label: 'Status',
    all_status: 'All Status',
    created_by_label: 'Created By',
    all_creators: 'All Creators',
    assigned_to_label: 'Assigned To',
    all_assignees: 'All Assignees',
    clear_all_btn: 'Clear all',
    to_label: 'To:',
    by_label: 'By:',
    seen_badge: 'Seen',
    no_snags_found: 'No snags found',
    snag_filter_empty_desc: 'Try changing your filters or add a new snag',
    edit_snag_title: 'Edit Snag',
    add_snag_title: 'Add Snag',
    click_attach_photo: 'Click to attach photo',
    photo_format_hint: 'Required — JPG, PNG, etc.',
    snag_title_placeholder: 'Snag title *',
    description_optional: 'Description (optional)',
    assign_to_placeholder: 'Assign to... *',
    voice_note_label: 'Voice Note',
    change_btn: 'Change',
    edit_btn: 'Edit',
    delete_btn: 'Delete',
    unassigned_label: 'Unassigned',
    last_response_title: 'Last Response',
    voice_response_label: 'Voice Response',
    update_status_respond_title: 'Update Status & Respond',
    add_comment_placeholder: 'Add a comment...',
    post_response_btn: 'Post Response',
    failed_load_snags: 'Failed to load snags',
    status_updated_to_msg: 'Status updated to {label}',
    failed_update_status: 'Failed to update status',
    select_image_file_msg: 'Please select an image file',
    title_required_msg: 'Title is required',
    assignee_required_msg: 'Assignee is required',
    photo_required_msg: 'Photo is required',
    snag_limit_msg: 'Limit Reached: You have reached your snag limit. Please upgrade your plan to add more snags.',
    snag_added_msg: 'Snag added',
    failed_add_snag: 'Failed to add snag',
    snag_updated_msg: 'Snag updated',
    failed_update_snag: 'Failed to update snag',
    confirm_delete_snag: 'Move "{title}" to Trash? It can be recovered later from your Profile settings for 30 days.',
    snag_deleted_msg: 'Snag deleted',
    failed_delete_snag: 'Failed to delete snag',
    only_assignee_update_msg: 'Only the assigned person can update the status',
    status_click_change_tip: 'Status: {label} — click to change',
    status_tip: 'Status: {label}',
    closed_status: 'CLOSED',
    request_for_info_title: 'Request for Information',
    new_rfi_btn: 'New RFI',
    all_creators_label: 'All Creators',
    all_assignees_label: 'All Assignees',
    by_user_label: 'by {name}',
    assigned_to_user_label: 'Assigned to {name}',
    attachments_count_label: '{count} attachments',
    no_rfis_found: 'No Request for Information found',
    rfi_filter_empty_desc: 'Try changing your filters or create a new RFI',
    edit_rfi_title: 'Edit Request for Information',
    new_rfi_title: 'New Request for Information',
    title_label: 'Title *',
    rfi_title_placeholder: 'Enter RFI title',
    description_label: 'Description',
    rfi_context_placeholder: 'Provide more context...',
    assign_to_label: 'Assign To *',
    select_assignee_placeholder: 'Select assignee *',
    expiry_date_label: 'Expiry Date',
    attachments_label: 'Attachments',
    create_rfi_btn: 'Create RFI',
    rfi_id_label: 'RFI #{id}',
    link_btn: 'Link',
    linked_folders_title: 'Linked Folders',
    voice_attachment_label: 'Voice Attachment',
    response_title: 'Response',
    update_response_title: 'Update Response',
    provide_response_title: 'Provide Response',
    rfi_response_placeholder: 'Type your response here...',
    response_attachments_label: 'Response Attachments',
    submit_response_btn: 'Submit Response',
    update_status_title: 'Update Status',
    failed_load_rfis: 'Failed to load RFIs',
    rfi_limit_msg: 'Limit Reached: You have reached your RFI limit. Please upgrade your plan to create more RFIs.',
    rfi_created_msg: 'RFI created successfully',
    failed_create_rfi: 'Failed to create RFI',
    links_updated_msg: 'Links updated successfully',
    failed_update_links: 'Failed to update links',
    rfi_updated_msg: 'RFI updated successfully',
    failed_update_rfi: 'Failed to update RFI',
    confirm_delete_rfi: 'Move this RFI to Trash? It can be recovered later from your Profile settings for 30 days.',
    rfi_deleted_msg: 'RFI deleted',
    failed_delete_rfi: 'Failed to delete RFI',
    response_updated_msg: 'Response updated',
    failed_update_response: 'Failed to update response',
    some_files_skipped_msg: 'Some files were skipped (not images)',
    max_4_photos_msg: 'Maximum 4 photos allowed',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    // Features
    feat_single_proj: 'Single Project Access',
    feat_up_to_5: 'Up to 5 Projects',
    feat_up_to_10: 'Up to 10 Projects',
    feat_above_10: 'Above 10 Projects',
    feat_client_view: 'Client Viewership',
    feat_basic_report: 'Basic Reporting',
    feat_struct_report: 'Structured Reporting',
    feat_ai_report: 'AI-Assisted Reports',
    feat_5gb: '5GB Cloud Storage',
    feat_25gb: '25GB Cloud Storage',
    feat_100gb: '100GB Cloud Storage',
    feat_above_100gb: 'Above 100GB Cloud Storage',
    feat_onetime: 'One-time purchase',
    feat_basic_dash: 'Basic Project Dashboard',
    feat_role_access: 'Role-Based Access',
    feat_media_doc: 'Media Documentation',
    feat_priority_supp: 'Priority Support',
    feat_custom_wf: 'Custom Workflows',
    feat_custom_onboard: 'Custom Onboarding',
    feat_dedic_supp: 'Dedicated Support',
    feat_custom_integ: 'Custom Integrations',
    feat_snag: 'Snag List Feature',
    feat_drawings: 'Drawings Release to Site',
    feat_multilingual: 'Multi-lingual Support (English, Hindi & Telugu)',
    feat_secure: 'Secure Data Storage',
    sub_onetime: 'Single project access',
    sub_starter: 'Up to 5 projects',
    sub_pro: 'Up to 10 projects',
    sub_enterprise: 'Above 10 projects',
    validity_90: 'Valid for 90 days',
    free_trial_14: '14 Day Free Trial',
    buy_now: 'Buy Now',
    get_started: 'Get Started',
    upgrade_pro: 'Upgrade to Pro',
    contact_sales: 'Contact Sales',
    failed_load_reports: 'Failed to load {type} report',
    manual_label: 'Manual',
    checklist_label: 'Checklist',
    failed_load_manuals: 'Failed to load manuals',
    uploaded_successfully: 'Uploaded successfully',
    upload_failed: 'Upload failed',
    confirm_remove_manual: 'Move "{name}" to Trash? It can be recovered later from your Profile settings for 30 days.',
    removed_msg: 'Removed',
    delete_failed: 'Delete failed',
    link_copied_msg: 'Link copied to clipboard',
    upload_manual_checklist_btn: 'Upload Manual / Checklist',
    type_label: 'Type',
    click_select_file_hint: 'Click to select PDF / Word / Excel',
    max_size_hint: 'Max size: 100 MB',
    upload_btn: 'Upload',
    copy_link_tip: 'Copy link',
    no_manuals_yet: 'No manuals or Checklists yet',
    assign_to: 'Assign To',
    optional: '(Optional)',
    unassigned: 'Unassigned',
    selectAssignee: 'Select Assignee',
    assigneeDescription: 'Assign this document to a project member',
    today: 'Today',
    yesterday: 'Yesterday',
    link_a_file: 'Link a File',
    search_files: 'Search files...',
    loading_files: 'Loading files...',
    no_files_matching: 'No files matching',
    go_up: 'Go Up',
    folder_is_empty: 'Folder is empty',
    link: 'Link',
    files: 'Files',
    file_details: 'File Details',
    uploaded_by: 'Uploaded By',
    system_label: 'SYSTEM',
    location_label: 'Location',
    downloading_label: 'DOWNLOADING...',
    download_file: 'DOWNLOAD FILE',
    discussion: 'Discussion',
    links_label: 'Links',
    no_linked_items: 'No linked items yet.',
    view_btn: 'View',
    remove_link: 'Remove Link',
    snag: 'Snag',
    view_original: 'View Original',
    zoom_out: 'Zoom Out',
    zoom_in: 'Zoom In',
    rotate: 'Rotate',
    exit_fullscreen: 'Exit Fullscreen',
    fullscreen: 'Fullscreen',
    preview_not_available: 'Preview not available for this file type',
    file_linked_success: 'File linked successfully',
    link_rfi: 'File linked to RFI successfully',
    link_snag: 'File linked to Snag successfully',
    file_link_failed: 'Failed to link file',
    link_removed_success: 'Link removed successfully',
    link_remove_failed: 'Failed to remove link',
    
    failed_create_snag: 'Failed to create snag',
  
    failed_delete_photos: 'Failed to delete photos',
    photo_unarchived_success: 'Photo unarchived successfully',
    failed_to_unarchive_photo: 'Failed to unarchive photo',
   
    select_photo_delete: 'Please select at least one photo to delete',
    protected_folder_delete_error: 'Files in system folders (Archive/Confirmations) cannot be deleted.',
    unauthorized_delete_error: 'You can only delete photos that you originally uploaded.',
    confirm_delete_multiple_photos: 'Move these {count} photos to Trash? They can be recovered later from Settings for 30 days.',
    photos_deleted_msg: 'Selected photos deleted successfully',
   
    unarchive_photo_tip: 'Unarchive photo',
  
    create_snag_photo_title: 'Create Snag from Photo',
    create_snag_photo_desc: 'Create a new snag linked to this photo. Fill in the details below.',
   
    enter_snag_title: 'Enter snag title',
 
    enter_snag_desc: 'Enter snag description',
    assignee_label: 'Assignee',
    select_assignee: 'Select Assignee',
    creating_btn: 'Creating...',
    create_snag_btn: 'Create Snag',
    create_rfi_photo_title: 'Create RFI from Photo',
    create_rfi_photo_desc: 'Create a new RFI linked to this photo. Fill in the details below.',
    enter_rfi_title: 'Enter RFI title',
    enter_rfi_desc: 'Enter RFI description',
    
    create_rfi: 'Create RFI',
    create_snag: 'Create Snag',
    confirmations_folder_name: 'Confirmations',
    'projectSnags.viewLinkedAttachments': 'View Linked Attachments',
    'projectRfi.viewLinkedAttachments': 'View Linked Attachments',
    rename_btn: 'Rename',
    rename_file_title: 'Rename File',
    rename_folder_title: 'Rename Folder',
    new_name_label: 'New Name',
    enter_new_name_placeholder: 'Enter new file name',
    renaming_btn: 'Renaming...',
    upload_new_version: 'Upload New Version',
    version_promoted_success: 'Version promoted to current active version',
    confirm_delete_version: 'Are you sure you want to delete this version?',
    version_deleted_success: 'Version deleted successfully',
    versions: 'Versions',
    loading_versions: 'Loading versions...',
    no_versions: 'No versions found',
    current_version: 'Active',
    make_active: 'Make Active',
  },
  hi: {
    welcome_back: 'वापसी पर स्वागत है',
    hi: 'नमस्ते',
    dashboard: 'डैशबोर्ड',
    upload: 'अपलोड',
    activity: 'गतिविधि',
    profile: 'प्रोफ़ाइल',
    snag_list: 'स्नैग सूची',
    user_mgmt: 'उपयोगकर्ता प्रबंधन',
    billing: 'प्लान/अपग्रेड',
    projects: 'परियोजनाएं',
    documents: 'दस्तावेज़',
    photos: 'तस्वीरें',
    sign_in: 'साइन इन',
    sign_up: 'साइन अप',
    sign_out: 'साइन आउट',
    settings: 'सेटिंग्स',
    analytics: 'एनालिटिक्स',
    notifications_label: 'सूचनाएं',
    chats: 'चैट्स',
    teams: 'टीम्स',
    org_users: 'संगठन उपयोगकर्ता',
    all_projects: 'सभी प्रोजेक्ट्स',
    organization_projects: 'संगठन प्रोजेक्ट्स',
    all_organizations: 'सभी संगठन',
    create_project: 'प्रोजेक्ट बनाएं',
    search: 'खोजें',
    notifications: 'सूचनाएं',
    help_support: 'सहायता और समर्थन',
    feedback: 'प्रतिक्रिया',
    your_projects: 'आपकी परियोजनाएं',
    total_projects: 'कुल परियोजनाएं',
    manage_projects: 'अपनी सभी कंपनी परियोजनाएं प्रबंधित करें',
    assigned_projects: 'अपनी सौंपी गई परियोजनाओं को देखें और योगदान दें',
    shared_projects: 'अपनी साझा परियोजना फ़ाइलें एक्सेस करें',
    no_projects: 'कोई परियोजना उपलब्ध नहीं',
    language: 'भाषा',
    english: 'अंग्रेज़ी',
    hindi: 'हिन्दी',
    telugu: 'తెలుగు',
    choose_plan: 'योजना चुनें',
    recommended: 'सुझाया गया',
    standard: 'स्टैंडर्ड',
    intermediate: 'इंटरमीडिएट',
    pro: 'प्रो',
    project_overview: 'परियोजना अवलोकन',
    back_to_projects: 'परियोजनाओं पर वापस जाएं',
    daily_reports: 'दैनिक रिपोर्ट',
    weekly_reports: 'साप्ताहिक रिपोर्ट',
    manuals: 'चेकलिस्ट',
    project_not_found: 'परियोजना नहीं मिली।',
    back_to_dashboard: 'डैशबोर्ड पर वापस जाएं',
    name_update_success: 'नाम सफलतापूर्वक अपडेट किया गया',
    name_update_error: 'नाम अपडेट करने में विफल',
    company_settings: 'कंपनी सेटिंग्स',
    company_name_label: 'कंपनी का नाम',
    company_name_placeholder: 'कंपनी का नाम दर्ज करें',
    company_name_success: 'कंपनी का नाम अपडेट किया गया',
    company_name_error: 'कंपनी का नाम अपडेट करने में विफल',
    company_logo_success: 'कंपनी का लोगो अपडेट किया गया',
    company_logo_error: 'कंपनी का लोगो अपलोड करने में विफल',
    tap_change_logo: 'लोगो बदलने के लिए टैप करें',
    change_password: 'पासवर्ड बदलें',
    current_password: 'वर्तमान पासवर्ड',
    new_password: 'नया पासवर्ड',
    confirm_password: 'नए पासवर्ड की पुष्टि करें',
    password_mismatch: 'पासवर्ड मेल नहीं खाते',
    password_success: 'पासवर्ड सफलतापूर्वक अपडेट किया गया',
    password_error: 'पासवर्ड अपडेट करने में विफल',
    update_password: 'पासवर्ड अपडेट करें',
    trash_management: 'ट्रैश प्रबंधन',
    trash_management_subtitle: 'हటాए गए प्रोजेक्ट्स को रिकवर या डिलीट करें',
    crop_photo_title: 'प्रोफ़ाइल फ़ोटो काटें',
    save_photo: 'फ़ोटो सहेजें',
    profile_pic_success: 'प्रोफ़ाइल चित्र सफलतापूर्वक अपडेट किया गया',
    profile_pic_error: 'प्रोफ़ाइल चित्र अपलोड करने में विफल',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    trash_title: 'ट्रैश',
    trash_subtitle: 'हटाए गए आइटम्स को प्रबंधित और पुनर्स्थापित करें',
    loading_trash: 'ट्रैश लोड हो रहा है...',
    trash_empty: 'ट्रैश खाली है',
    trash_empty_desc: 'हटाए गए आइटम्स स्थायी रूप से हटाए जाने से पहले 30 दिनों तक यहां दिखाई देंगे।',
    day_left: 'दिन शेष',
    days_left: 'दिन शेष',
    no_description: 'कोई विवरण उपलब्ध नहीं',
    deleted_at: 'हटाया गया',
    restore: 'पुनर्स्थापित करें',
    delete_forever: 'हमेशा के लिए हटा दें',
    restore_success: 'आइटम सफलतापूर्वक पुनर्स्थापित किया गया',
    restore_error: 'आइटम को पुनर्स्थापित करने में विफल',
    permanent_delete_success: 'आइटम स्थायी रूप से हटा दिया गया',
    permanent_delete_error: 'आइटम को हटाने में विफल',
    load_trash_error: 'ट्रैश लोड करने में विफल',
    permanent_delete_confirm: 'क्या आप वाकई ऐसा करना चाहते हैं? यह इस आइटम को स्थायी रूप से हटा देगा। इसे पूर्ववत नहीं किया जा सकता।',
    no_permission: 'आपको इस पृष्ठ को देखने की अनुमति नहीं है।',
    load_users_error: 'उपयोगकर्ताओं को लोड करने में विफल',
    invalid_email: 'कृपया एक मान्य ईमेल दर्ज करें',
    select_project_role: 'कृपया इस भूमिका के लिए एक प्रोजेक्ट चुनें',
    invite_success: 'निमंत्रण सफलतापूर्वक भेजा गया',
    invite_error: 'निमंत्रण भेजने में विफल',
    remove_access_success: 'प्रोजेक्ट एक्सेस सफलतापूर्वक हटा दिया गया',
    remove_access_error: 'प्रोजेक्ट एक्सेस हटाने में विफल',
    link_copied: 'लिंक क्लिपबोर्ड पर कॉपी किया गया',
    user_mgmt_subtitle: 'संगठन के सदस्यों और भूमिकाओं को प्रबंधित करें।',
    add_member: 'सदस्य जोड़ें',
    email_address: 'ईमेल पता',
    role: 'भूमिका',
    assign_project: 'प्रोजेक्ट सौंपें',
    choose_project: 'प्रोजेक्ट चुनें',
    no_projects_found: 'कोई प्रोजेक्ट नहीं मिला',
    invite: 'आमंत्रित करें',
    project_access_links: 'प्रोजेक्ट एक्सेस लिंक',
    project_access_links_subtitle: 'आंतरिक योगदानकर्ताओं और बाहरी ग्राहकों के लिए सीधे लॉगिन लिंक जेनरेट करें।',
    select_project_placeholder: 'एक प्रोजेक्ट चुनें',
    contributor_access: 'योगदानकर्ता एक्सेस',
    client_access: 'ग्राहक एक्सेस',
    copy_link: 'लिंक कॉपी करें',
    copied: 'कॉपी किया गया',
    no_project_selected: 'कोई प्रोजेक्ट नहीं चुना गया',
    no_project_selected_subtitle: 'योगदानकर्ताओं और ग्राहकों के लिए सीधे एक्सेस लिंक जेनरेट करने के लिए कृपया ऊपर दिए गए ड्रॉपडाउन से एक प्रोजेक्ट चुनें।',
    member: 'सदस्य',
    status: 'स्थिति',
    joined: 'शामिल हुए',
    actions: 'कार्रवाई',
    invited_user: 'आमंत्रित उपयोगकर्ता',
    no_contact_info: 'कोई संपर्क जानकारी नहीं',
    all_projects_label: '(सभी प्रोजेक्ट्स)',
    no_projects_assigned: 'कोई प्रोजेक्ट नहीं सौंपा गया',
    verified: 'सत्यापित',
    pending: 'लंबित',
    no_users_found: 'आपके संगठन में कोई उपयोगकर्ता नहीं मिला।',
    remove_access_title: 'प्रोजेक्ट एक्सेस हटाएं?',
    remove_access_confirm: 'क्या आप वाकई {name} को उनके प्रोजेक्ट एक्सेस से हटाना चाहते हैं? उपयोगकर्ता खाता संगठन में रहेगा।',
    remove_access_button: 'एक्सेस हटाएं',
    blocked_users: 'अवरुद्ध उपयोगकर्ता',
    active_members: 'सक्रिय सदस्य',
    unblock: 'अवरोध हटाएँ',
    just_delete: 'केवल हटाएं',
    block_and_delete: 'ब्लॉक करें और हटाएं',
    unblock_success: 'उपयोगकर्ता का अवरोध सफलतापूर्वक हटा दिया गया',
    unblock_error: 'उपयोगकर्ता का अवरोध हटाने में विफल',
    admin: 'व्यवस्थापक',
    contributor: 'योगदानकर्ता',
    client: 'ग्राहक',
    // Billing
    billing_subtitle: 'अपनी टीम के लिए उपयुक्त योजना चुनें',
    monthly: 'मासिक',
    annual: 'वार्षिक',
    save_35: '35% बचाएं',
    plans_tab: 'योजनाएं',
    usage_tab: 'उपयोग',
    history_tab: 'इतिहास',
    most_popular: 'सबसे लोकप्रिय',
    billed_annually: 'सालाना बिल किया गया',
    incl_gst: '(18% जीएसटी सहित)',
    processing: 'प्रसंस्करण...',
    current_plan: 'वर्तमान योजना',
    resource_consumption: 'संसाधन खपत',
    resource_consumption_subtitle: 'आपके संगठन के संसाधन उपयोग का विस्तृत विवरण',
    plan_validity: 'योजना की वैधता',
    active_projects: 'सक्रिय परियोजनाएं',
    cloud_storage: 'क्लाउड स्टोरेज',
    team_members: 'टीम के सदस्य',
    clients: 'ग्राहक',
    snags: 'कमियां (Snags)',
    rfis: 'RFIs',
    active_status: 'सक्रिय',
    no_payment_history: 'कोई भुगतान इतिहास नहीं मिला।',
    invoice: 'इनवॉइस',
    cycle: 'चक्र',
    amount: 'राशि',
    date: 'तारीख',
    action: 'कार्रवाई',
    limit: 'सीमा',
    payment_success: 'भुगतान सफल! आपकी योजना अपग्रेड कर दी गई है।',
    payment_failed: 'भुगतान विफल',
    payment_error: 'भुगतान में कुछ गलत हो गया।',
    payment_sdk_error: 'रेजरपे SDK लोड करने में विफल रहा। कृपया अपना इंटरनेट कनेक्शन जांचें।',
    payment_verification_failed: 'भुगतान सत्यापन विफल रहा। कृपया सहायता से संपर्क करें।',
    price_custom: 'कस्टम',
    // Chats
    access_denied: 'पहुंच वर्जित',
    superadmin_chat_no_access: 'सुपरएडमिन के पास चैट सुविधा तक पहुंच नहीं है।',
    loading_chats: 'चैट लोड हो रही है...',
    search_chats: 'चैट खोजें...',
    no_chats_found: 'कोई चैट नहीं मिली',
    chat_fallback: 'चैट',
    more_projects: '+{count} और',
    user_is_typing: '{name} टाइप कर रहा है...',
    photo: 'फोटो',
    file: 'फाइल',
    group_chat: 'ग्रुप चैट',
    direct_message: 'डायरेक्ट मैसेज',
    loading_messages: 'संदेश लोड हो रहे हैं...',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    members_count: '{count} सदस्य',
    user_fallback: 'उपयोगकर्ता',
    voice_note: 'वॉयस नोट',
    photo_message: 'फोटो',
    file_message: 'फाइल',
    message_fallback: 'संदेश',
    replied_to_message: 'संदेश का उत्तर दिया',
    message_placeholder: 'संदेश लिखें...',
    new_group: 'नया ग्रुप',
    new_direct_chat: 'नई डायरेक्ट चैट',
    search_people: 'लोगों को खोजें...',
    group_name_placeholder: 'ग्रुप का नाम',
    users_selected: '{count} चयनित',
    create_group_btn: 'ग्रुप बनाएं ({count})',
    create_chat_btn: 'चैट बनाएं',
    enter_group_name: 'कृपया ग्रुप का नाम दर्ज करें',
    failed_create_chat: 'चैट बनाने में विफल',
    all_actions: 'सभी गतिविधियाँ',
    snags_label: 'कमियां (Snags)',
    rfi_label: 'RFI',
    members_label: 'सदस्य',
    back_to_unread: 'अपठित पर वापस जाएं',
    history: 'इतिहास',
    notifications_subtitle: 'परियोजना परिवर्तनों के साथ अपडेट रहें',
    mark_all_read: 'सभी को पढ़ा हुआ मानें',
    all_users: 'सभी उपयोगकर्ता',
    no_notifications_48h: 'पिछले 48 घंटों में कोई सूचना नहीं',
    no_new_notifications: 'कोई नई सूचना नहीं',
    all_caught_up: 'आप पूरी तरह से अपडेट हैं!',
    activity_subtitle: 'आपकी परियोजनाओं से अपडेट',
    no_recent_activity: 'कोई हालिया गतिविधि नहीं',
    team_mgmt_hub: 'टीम प्रबंधन केंद्र',
    filter_access_control: 'फ़िल्टर और एक्सेस कंट्रोल',
    project_access: 'प्रोजेक्ट एक्सेस',
    team_role: 'टीम भूमिका',
    all_roles: 'सभी भूमिकाएँ',
    reset: 'रीसेट करें',
    copy_contributor_link: 'योगदानकर्ता लिंक कॉपी करें',
    copy_client_link: 'क्लाइंट लिंक कॉपी करें',
    no_users_filter: 'आपके फ़िल्टर से मेल खाने वाला कोई उपयोगकर्ता नहीं मिला।',
    excellent: 'उत्कृष्ट',
    moderate: 'मध्यम',
    attention_needed: 'ध्यान देने की आवश्यकता',
    access_restricted_admins: 'पहुंच केवल व्यवस्थापकों तक सीमित है।',
    go_back: 'वापस जाएं',
    admin_analytics: 'व्यवस्थापक विश्लेषिकी',
    analytics_subtitle: 'कंपनी-व्यापी परियोजना बुद्धिमत्ता',
    tasks_pending: 'लंबित कार्य',
    tasks_overdue: 'विलंबित कार्य',
    delayed_projects: 'विलंबित परियोजनाएं',
    avg_completion: 'औसत पूर्णता',
    project_status: 'परियोजना की स्थिति',
    task_completion_trend: 'कार्य पूर्णता प्रवृत्ति',
    completed_label: 'पूर्ण',
    created_label: 'बनाया गया',
    communication_activity: 'संचार गतिविधि',
    messages_week: 'इस सप्ताह के संदेश',
    project_pulse_score: 'प्रोजेक्ट पल्स स्कोर',
    pulse: 'पल्स',
    progress: 'प्रगति',
    snags_pt: 'कमियां (P/T)',
    rfis_pt: 'RFIs (P/T)',
    risk: 'जोखिम',
    team_leaderboard: 'टीम लीडरबोर्ड',
    tasks_count: '{count} कार्य',
    avg_label: 'औसत:',
    live_activity: 'लाइव गतिविधि',
    critical_issue_summary: 'महत्वपूर्ण समस्या सारांश',
    open_snags: 'खुली कमियां',
    overdue_items: 'विलंबित आइटम',
    active_rfis: 'सक्रिय RFIs',
    file_uploads_week: 'इस सप्ताह के फाइल अपलोड',
    sort_by: 'इसके द्वारा क्रमबद्ध करें:',
    sort_projects_by: 'परियोजनाओं को क्रमबद्ध करें',
    name_label: 'नाम',
    newest: 'नवीनतम',
    oldest: 'सबसे पुराना',
    create_new_project: 'नई परियोजना बनाएं',
    project_name_max: 'परियोजना का नाम (अधिकतम 25)',
    company_client_max: 'कंपनी का नाम/क्लाइंट का नाम (अधिकतम 50)',
    enter_company_client: 'कंपनी/क्लाइंट का नाम दर्ज करें',
    start_date: 'आरंभ तिथि',
    end_date: 'अंतिम तिथि',
    no_company_client: 'कोई कंपनी/क्लाइंट नाम नहीं',
    contributor_label: 'योगदानकर्ता:',
    client_label: 'क्लाइंट:',
    copied_to_clipboard: 'क्लिपबोर्ड पर कॉपी किया गया',
    org_logo_updated: 'संगठन का लोगो अपडेट किया गया',
    logo_upload_failed: 'लोगो अपलोड विफल रहा',
    project_limit_reached: 'सीमा पूरी हो गई: आप अपनी परियोजना सीमा तक पहुँच गए हैं। अधिक परियोजनाएं बनाने के लिए कृपया अपना प्लान अपग्रेड करें।',
    upgrade_label: 'अपग्रेड करें',
    project_created_success: 'परियोजना सफलतापूर्वक बनाई गई',
    project_create_failed: 'परियोजना बनाने में विफल',
    login_to_view_dashboard: 'डैशबोर्ड देखने के लिए कृपया लॉग इन करें।',
    logo_placeholder: 'लोगो',
    crop_logo: 'लोगो क्रॉप करें',
    upload_logo_btn: 'लोगो अपलोड करें',
    no_logo: 'कोई लोगो नहीं',
    org_logo_title: 'संगठन का लोगो',
    logo_represents: 'यह लोगो {name} का प्रतिनिधित्व करता है।',
    change_logo: 'लोगो बदलें',
    loading_overview: 'परियोजना अवलोकन लोड हो रहा है...',
    failed_load_members: 'सदस्यों को लोड करने में विफल',
    project_access_removed: 'परियोजना एक्सेस हटा दिया गया',
    failed_remove_access: 'परियोजना एक्सेस हटाने में विफल',
    export_completed: 'निर्यात {count} सेकंड में पूरा हुआ!',
    export_failed: 'निर्यात विफल रहा: {error}',
    starting_export: 'निर्यात प्रक्रिया शुरू हो रही है...',
    failed_trigger_export: 'निर्यात ट्रिगर करने में विफल',
    failed_share_link: 'शेयर लिंक बनाने में विफल रहा',
    client_project_code: 'क्लाइंट प्रोजेक्ट कोड',
    active_label: 'सक्रिय',
    reports_label: 'रिपोर्ट',
    files_label: 'फ़ाइलें',
    view_reports: 'रिपोर्ट देखें',
    open_issues: 'खुली समस्याएं',
    access_codes: 'एक्सेस कोड',
    contributor_code_label: 'योगदानकर्ता कोड',
    client_list_label: 'क्लाइंट सूची',
    code_restricted: 'कोड प्रतिबंधित',
    client_code_label: 'क्लाइंट कोड',
    final_handover_report: 'अंतिम हैंडओवर रिपोर्ट',
    exporting_label: 'निर्यात हो रहा है...',
    time_left: '{time} शेष',
    report_ready: 'रिपोर्ट तैयार है',
    generated_label: 'जनरेट किया गया',
    download_label: 'डाउनलोड',
    generate_new_report: 'नई रिपोर्ट जनरेट करें',
    export_final_handover: 'अंतिम हैंडओवर रिपोर्ट निर्यात करें',
    no_active_members: 'कोई सक्रिय {role} नहीं मिला',
    primary_label: '(प्राथमिक)',
    edit_project: 'परियोजना संपादित करें',
    save_changes: 'परिवर्तन सहेजें',
    project_updated_success: 'परियोजना सफलतापूर्वक अपडेट की गई',
    project_update_failed: 'परियोजना अपडेट करने में विफल',
    confirm_delete_project: 'क्या आप वाकई इस परियोजना को हटाना चाहते हैं? इसे ट्रैश में ले जाया जाएगा और बाद में आपकी प्रोफ़ाइल सेटिंग्स से 30 दिनों तक पुनर्प्राप्त किया जा सकता है।',
    project_moved_trash: 'परियोजना ट्रैश में स्थानांतरित की गई',
    delete_project_failed: 'परियोजना हटाने में विफल। कृपया पुन: प्रयास करें।',
    deleting_project: 'परियोजना हटाई जा रही है',
    wait_cleaning_assets: 'कृपया प्रतीक्षा करें जब तक हम सभी संपत्तियों को साफ कर रहे हैं...',
    doc_marked_visible: 'दस्तावेज़ क्लाइंट के लिए दृश्यमान चिह्नित किया गया',
    doc_marked_hidden: 'दस्तावेज़ क्लाइंट के लिए छिपा हुआ चिह्नित किया गया',
    failed_toggle_visibility: 'दृश्यता बदलने में विफल',
    doc_marked_dnf: "दस्तावेज़ को 'फॉलो न करें' के रूप में चिह्नित किया गया",
    doc_unmarked_dnf: "दस्तावेज़ को 'फॉलो न करें' से हटा दिया गया",
    failed_toggle_dnf: 'फॉलो न करें को बदलने में विफल',
    doc_marked_ofr: "दस्तावेज़ को 'केवल संदर्भ के लिए' के रूप में चिह्नित किया गया",
    doc_unmarked_ofr: "दस्तावेज़ को 'केवल संदर्भ के लिए' से हटा दिया गया",
    failed_toggle_ofr: 'केवल संदर्भ के लिए बदलने में विफल',
    folder_marked_visible: 'फ़ोल्डर क्लाइंट के लिए दृश्यमान चिह्नित किया गया',
    folder_marked_hidden: 'फ़ोल्डर क्लाइंट के लिए छिपा हुआ चिह्नित किया गया',
    archive_confirm_msg: 'क्या आप वाकई इस दस्तावेज़ को आर्काइव करना चाहते हैं? इसे आर्काइव फ़ोल्डर में ले जाया जाएगा और "फॉलो न करें" पर सेट किया जाएगा।',
    doc_archived: 'दस्तावेज़ आर्काइव किया गया',
    failed_archive_doc: 'दस्तावेज़ आर्काइव करने में विफल',
    archive_name_reserved: "'Archive' नाम सिस्टम उपयोग के लिए आरक्षित है",
    folder_created_msg: 'फ़ोल्डर "{name}" बनाया गया',
    create_folder_title: 'नया फ़ोल्डर बनाएं',
    folder_name_label: '{type} के लिए फ़ोल्डर का नाम',
    folder_name_placeholder: 'फ़ोल्डर का नाम दर्ज करें',
    create_folder_btn: 'फ़ोल्डर बनाएं',
    failed_create_folder: 'फ़ोल्डर बनाने में विफल',
    folder_renamed_msg: 'फ़ोल्डर का नाम बदलकर "{name}" कर दिया गया',
    failed_rename_folder: 'फ़ोल्डर का नाम बदलने में विफल',
    file_renamed_msg: 'फ़ाइल का नाम बदलकर "{name}" कर दिया गया',
    failed_rename_file: 'फ़ाइल का नाम बदलने में विफल',
    confirm_delete_folder: 'क्या फ़ोल्डर "{name}" को ट्रैश में भेजना है? इसे बाद में आपकी प्रोफ़ाइल सेटिंग्स से 30 दिनों तक रिकवर किया जा सकता है।',
    folder_deleted_msg: 'फ़ोल्डर "{name}" हटाया गया',
    failed_delete_folder: 'फ़ोल्डर हटाने में विफल',
    folder_already_empty: 'फ़ोल्डर पहले से ही खाली है',
    visibility_updated_msg: '{count} मदों के लिए दृश्यता अपडेट की गई',
    dnf_updated_msg: "{count} फ़ाइलों के लिए 'फॉलो न करें' अपडेट किया गया",
    select_file_share: 'साझा करने के लिए कम से कम एक फ़ाइल चुनें',
    upload_file_btn: 'फ़ाइल अपलोड करें',
    new_folder_btn: 'नया फ़ोल्डर',
    select_btn: 'चुनें',
    grid_view_tip: 'ग्रिड दृश्य',
    list_view_tip: 'सूची दृश्य',
    sort_by_label: 'क्रमबद्ध करें:',
    sort_docs_title: 'दस्तावेज़ क्रमबद्ध करें',
    date_label: 'संशोधित तिथि',
    size_label: 'आकार',
    files_folders_tab: 'फ़ाइलें और फ़ोल्डर',
    linked_rfi_tab: 'लिंक्ड RFI',
    linked_rfi_and_snag_tab: 'लिंक्ड RFI और स्नैग',
    move_folder_tip: 'फ़ोल्डर ले जाएं',
    rename_folder_tip: 'फ़ोल्डर का नाम बदलें',
    files_count_label: '{count} फ़ाइलें',
    folder_count_label: '{count} फ़ोल्डर',
    folders_count_label: '{count} फ़ोल्डर',
    share_link_tip: 'लिंक के माध्यम से साझा करें',
    rename_file_tip: 'फ़ाइल का नाम बदलें',
    toggle_visibility_tip: 'दृश्यता बदलें',
    toggle_dnf_tip: 'फॉलो न करें बदलें',
    move_file_tip: 'फ़ाइल ले जाएं',
    archive_file_tip: 'फ़ाइल आर्काइव करें',
    dnf_tag: 'DNF',
    do_not_follow_tag: 'फॉलो न करें',
    toggle_ofr_tip: 'केवल संदर्भ के लिए टॉगल करें',
    ofr_tag: 'OFR',
    only_for_reference_tag: 'केवल संदर्भ के लिए',
    toggle_client_vis_tip: 'क्लाइंट दृश्यता बदलें',
    no_docs_yet: 'अभी तक कोई फ़ोल्डर या दस्तावेज़ नहीं है',
    items_selected: '{count} चयनित',
    share_btn: 'साझा करें',
    move_btn: 'ले जाएं',
    show_btn: 'दिखाएं',
    hide_btn: 'छिपाएं',
    regular_btn: 'नियमित',
    clear_selection_tip: 'चयन साफ़ करें',
    folder_deleted_move_msg: 'सामग्री ले जाने के बाद फ़ोल्डर "{name}" हटा दिया गया',
    failed_delete_empty_folder: 'सामग्री ले जाई गई, लेकिन खाली फ़ोल्डर हटाने में विफल',
    folder_not_empty_title: 'फ़ोल्डर खाली नहीं है',
    folder_not_empty_desc: 'फ़ोल्डर {name} में फ़ाइलें या उप-फ़ोल्डर हैं। आप कैसे आगे बढ़ना चाहेंगे?',
    delete_everything_btn: 'सब कुछ हटाएं',
    delete_everything_desc: 'फ़ोल्डर और उसकी सभी सामग्री को स्थायी रूप से हटा दें',
    move_contents_first_btn: 'पहले सामग्री ले जाएं',
    move_contents_first_desc: 'अंदर की मदों के लिए दूसरा पथ चुनें',
    photo_marked_visible: 'फोटो क्लाइंट के लिए दृश्यमान चिह्नित की गई',
    photo_marked_hidden: 'फोटो क्लाइंट के लिए छिपी हुई चिह्नित की गई',
    photo_marked_dnf: "फोटो को 'फॉलो न करें' के रूप में चिह्नित किया गया",
    photo_unmarked_dnf: "फोटो को 'फॉलो न करें' से हटा दिया गया",
    confirm_delete_photo: 'क्या इस फोटो को ट्रैश में भेजना है? इसे बाद में आपकी प्रोफ़ाइल सेटिंग्स से 30 दिनों तक रिकवर किया जा सकता है।',
    photo_deleted_msg: 'फोटो हटा दी गई',
    failed_delete_photo: 'फोटो हटाने में विफल',
    select_photo_share: 'साझा करने के लिए कम से कम एक फोटो चुनें',
    upload_photo_btn: 'फोटो अपलोड करें',
    sort_photos_title: 'फोटो क्रमबद्ध करें',
    photos_folders_tab: 'फोटो और फ़ोल्डर',
    delete_folder_tip: 'फ़ोल्डर हटाएं',
    photos_count_label: '{count} फोटो',
    delete_photo_tip: 'फोटो हटाएं',
    no_photos_yet: 'अभी तक कोई फ़ोल्डर या फोटो नहीं है',
    daily_label: 'दैनिक',
    weekly_label: 'साप्ताहिक',
    monthly_label: 'मासिक',
    daily_report: 'दैनिक रिपोर्ट',
    weekly_report: 'साप्ताहिक रिपोर्ट',
    monthly_report: 'मासिक रिपोर्ट',
    generating_label: 'जनरेट हो रहा है...',
    generate_report_btn: '{type} रिपोर्ट जनरेट करें',
    report_period_to: 'से',
    download_pdf_tip: 'PDF डाउनलोड करें',
    no_detail_records: 'इस अवधि के लिए कोई विवरण रिकॉर्ड नहीं है',
    docs_uploaded_title: 'दस्तावेज़ अपलोड किए गए',
    photos_uploaded_title: 'फोटो अपलोड की गईं',
    uploaded_by_in: '({folder} में {user} द्वारा)',
    photos_by_in: '{folder} में {user} द्वारा {count} फोटो',
    no_reports_found: 'कोई {type} रिपोर्ट नहीं मिली',
    generate_to_start: 'शुरू करने के लिए एक जनरेट करें',
    export_options_title: 'निर्यात विकल्प',
    export_options_subtitle: 'अपनी रिपोर्ट में शामिल करने के लिए अनुभाग चुनें',
    waiting_clearance: 'निकासी की प्रतीक्षा है',
    open_status: 'खुला',
    completed_status: 'पूर्ण',
    resolved_status: 'समाधान किया गया',
    no_action_required: 'किसी कार्रवाई की आवश्यकता नहीं',
    overdue_status: 'विलंबित',
    project_snags_title: 'प्रोजेक्ट स्नैग',
    add_snag_btn: 'स्नैग जोड़ें',
    status_label: 'स्थिति',
    all_status: 'सभी स्थिति',
    created_by_label: 'द्वारा बनाया गया',
    all_creators: 'सभी निर्माता',
    assigned_to_label: 'को सौंपा गया',
    all_assignees: 'सभी प्राप्तकर्ता',
    clear_all_btn: 'सभी साफ़ करें',
    to_label: 'को:',
    by_label: 'द्वारा:',
    seen_badge: 'देखा गया',
    no_snags_found: 'कोई स्नैग नहीं मिला',
    snag_filter_empty_desc: 'अपने फ़िल्टर बदलने का प्रयास करें या एक नया स्नैग जोड़ें',
    edit_snag_title: 'स्नैग संपादित करें',
    add_snag_title: 'स्नैग जोड़ें',
    click_attach_photo: 'फोटो अटैच करने के लिए क्लिक करें',
    photo_format_hint: 'आवश्यक — JPG, PNG, आदि।',
    snag_title_placeholder: 'स्नैग शीर्षक *',
    description_optional: 'विवरण (वैकल्पिक)',
    assign_to_placeholder: 'को सौंपें... *',
    voice_note_label: 'वॉयस नोट',
    change_btn: 'बदलें',
    edit_btn: 'संपादित करें',
    delete_btn: 'हटाएं',
    unassigned_label: 'अनदेखा',
    last_response_title: 'पिछली प्रतिक्रिया',
    voice_response_label: 'वॉयस प्रतिक्रिया',
    update_status_respond_title: 'स्थिति अपडेट करें और प्रतिक्रिया दें',
    add_comment_placeholder: 'एक टिप्पणी जोड़ें...',
    post_response_btn: 'प्रतिक्रिया पोस्ट करें',
    failed_load_snags: 'स्नैग लोड करने में विफल',
    status_updated_to_msg: 'स्थिति {label} पर अपडेट की गई',
    failed_update_status: 'स्थिति अपडेट करने में विफल',
    select_image_file_msg: 'कृपया एक इमेज फ़ाइल चुनें',
    title_required_msg: 'शीर्षक आवश्यक है',
    assignee_required_msg: 'प्राप्तकर्ता आवश्यक है',
    photo_required_msg: 'फोटो आवश्यक है',
    snag_limit_msg: 'सीमा समाप्त: आप अपनी स्नैग सीमा तक पहुँच गए हैं। अधिक स्नैग जोड़ने के लिए कृपया अपना प्लान अपग्रेड करें।',
    snag_added_msg: 'स्नैग जोड़ा गया',
    failed_add_snag: 'स्नैग जोड़ने में विफल',
    snag_updated_msg: 'स्नैग अपडेट किया गया',
    failed_update_snag: 'स्नैग अपडेट करने में विफल',
    confirm_delete_snag: 'क्या "{title}" को ट्रैश में भेजना है? इसे बाद में आपकी प्रोफ़ाइल सेटिंग्स से 30 दिनों तक रिकवर किया जा सकता है।',
    snag_deleted_msg: 'स्नैग हटा दिया गया',
    failed_delete_snag: 'स्नैग हटाने में विफल',
    only_assignee_update_msg: 'केवल सौंपा गया व्यक्ति ही स्थिति अपडेट कर सकता है',
    status_click_change_tip: 'स्थिति: {label} — बदलने के लिए क्लिक करें',
    status_tip: 'स्थिति: {label}',
    closed_status: 'बंद',
    request_for_info_title: 'सूचना के लिए अनुरोध',
    new_rfi_btn: 'नया RFI',
    all_creators_label: 'सभी निर्माता',
    all_assignees_label: 'सभी प्राप्तकर्ता',
    by_user_label: '{name} द्वारा',
    assigned_to_user_label: '{name} को सौंपा गया',
    attachments_count_label: '{count} अटैचमेंट',
    no_rfis_found: 'सूचना के लिए कोई अनुरोध नहीं मिला',
    rfi_filter_empty_desc: 'अपने फ़िल्टर बदलने का प्रयास करें या एक नया RFI बनाएं',
    edit_rfi_title: 'सूचना के लिए अनुरोध संपादित करें',
    new_rfi_title: 'सूचना के लिए नया अनुरोध',
    title_label: 'शीर्षक *',
    rfi_title_placeholder: 'RFI शीर्षक दर्ज करें',
    description_label: 'विवरण',
    rfi_context_placeholder: 'अधिक संदर्भ प्रदान करें...',
    assign_to_label: 'को सौंपें *',
    select_assignee_placeholder: 'प्राप्तकर्ता चुनें *',
    expiry_date_label: 'समाप्ति तिथि',
    attachments_label: 'अटैचमेंट',
    create_rfi_btn: 'RFI बनाएं',
    rfi_id_label: 'RFI #{id}',
    link_btn: 'लिंक',
    linked_folders_title: 'लिंक्ड फ़ोल्डर',
    voice_attachment_label: 'वॉयस अटैचमेंट',
    response_title: 'प्रतिक्रिया',
    update_response_title: 'प्रतिक्रिया अपडेट करें',
    provide_response_title: 'प्रतिक्रिया प्रदान करें',
    rfi_response_placeholder: 'अपनी प्रतिक्रिया यहाँ टाइप करें...',
    response_attachments_label: 'प्रतिक्रिया अटैचमेंट',
    submit_response_btn: 'प्रतिक्रिया सबमिट करें',
    update_status_title: 'स्थिति अपडेट करें',
    failed_load_rfis: 'RFI लोड करने में विफल',
    rfi_limit_msg: 'सीमा समाप्त: आप अपनी RFI सीमा तक पहुँच गए हैं। अधिक RFI बनाने के लिए कृपया अपना प्लान अपग्रेड करें।',
    rfi_created_msg: 'RFI सफलतापूर्वक बनाया गया',
    failed_create_rfi: 'RFI बनाने में विफल',
    links_updated_msg: 'लिंक सफलतापूर्वक अपडेट किए गए',
    failed_update_links: 'लिंक अपडेट करने में विफल',
    rfi_updated_msg: 'RFI सफलतापूर्वक अपडेट किया गया',
    failed_update_rfi: 'RFI अपडेट करने में विफल',
    confirm_delete_rfi: 'क्या इस RFI को ट्रैश में भेजना है? इसे बाद में आपकी प्रोफ़ाइल सेटिंग्स से 30 दिनों तक रिकवर किया जा सकता है।',
    rfi_deleted_msg: 'RFI हटा दिया गया',
    failed_delete_rfi: 'RFI हटाने में विफल',
    response_updated_msg: 'प्रतिक्रिया अपडेट की गई',
    failed_update_response: 'प्रतिक्रिया अपडेट करने में विफल',
    some_files_skipped_msg: 'कुछ फ़ाइलें छोड़ दी गईं (इमेज नहीं)',
    max_4_photos_msg: 'अधिकतम 4 फोटो की अनुमति है',
    low: 'कम',
    medium: 'मध्यम',
    high: 'उच्च',
    // Features
    feat_single_proj: 'एकल परियोजना एक्सेस',
    feat_up_to_5: '5 परियोजनाओं तक',
    feat_up_to_10: '10 परियोजनाओं तक',
    feat_above_10: '10 से अधिक परियोजनाएं',
    feat_client_view: 'क्लाइंट व्यूअरशिप',
    feat_basic_report: 'बुनियादी रिपोर्टिंग',
    feat_struct_report: 'संरचित रिपोर्टिंग',
    feat_ai_report: 'AI-सहायता प्राप्त रिपोर्ट',
    feat_5gb: '5GB क्लाउड स्टोरेज',
    feat_25gb: '25GB क्लाउड स्टोरेज',
    feat_100gb: '100GB क्लाउड स्टोरेज',
    feat_above_100gb: '100GB से अधिक क्लाउड स्टोरेज',
    feat_onetime: 'एक बार की खरीद',
    feat_basic_dash: 'बुनियादी प्रोजेक्ट डैशबोर्ड',
    feat_role_access: 'भूमिका आधारित एक्सेस',
    feat_media_doc: 'मीडिया दस्तावेजीकरण',
    feat_priority_supp: 'प्राथमिकता सहायता',
    feat_custom_wf: 'कस्टम वर्कफ़्लो',
    feat_custom_onboard: 'कस्टम ऑनबोर्डिंग',
    feat_dedic_supp: 'समर्पित सहायता',
    feat_custom_integ: 'कस्टम एकीकरण',
    feat_snag: 'स्नैग लिस्ट फीचर',
    feat_drawings: 'साइट पर चित्र रिलीज',
    feat_multilingual: 'बहुभाषी सहायता (अंग्रेजी, हिंदी और तेलुगु)',
    feat_secure: 'सुरक्षित डेटा स्टोरेज',
    sub_onetime: 'एकल परियोजना एक्सेस',
    sub_starter: '5 परियोजनाओं तक',
    sub_pro: '10 परियोजनाओं तक',
    sub_enterprise: '10 से अधिक परियोजनाएं',
    validity_90: '90 दिनों के लिए मान्य',
    free_trial_14: '14 दिन का मुफ्त परीक्षण',
    buy_now: 'अभी खरीदें',
    get_started: 'शुरू करें',
    upgrade_pro: 'प्रो में अपग्रेड करें',
    contact_sales: 'बिक्री टीम से संपर्क करें',
    failed_load_reports: '{type} रिपोर्ट लोड करने में विफल',
    manual_label: 'मैनुअल',
    checklist_label: 'चेकलिस्ट',
    failed_load_manuals: 'मैनुअल लोड करने में विफल',
    uploaded_successfully: 'सफलतापूर्वक अपलोड किया गया',
    upload_failed: 'अपलोड विफल रहा',
    confirm_remove_manual: 'क्या "{name}" को ट्रैश में भेजना है? इसे बाद में आपकी प्रोफ़ाइल सेटिंग्स से 30 दिनों तक रिकवर किया जा सकता है।',
    removed_msg: 'हटा दिया गया',
    delete_failed: 'हटाना विफल रहा',
    link_copied_msg: 'लिंक क्लिपबोर्ड पर कॉपी किया गया',
    upload_manual_checklist_btn: 'मैनुअल / चेकलिस्ट अपलोड करें',
    type_label: 'प्रकार',
    click_select_file_hint: 'PDF / Word / Excel चुनने के लिए क्लिक करें',
    max_size_hint: 'अधिकतम आकार: 100 MB',
    upload_btn: 'अपलोड',
    copy_link_tip: 'लिंक कॉपी करें',
    no_manuals_yet: 'अभी तक कोई मैनुअल या चेकलिस्ट नहीं है',
    assign_to: 'किसे सौंपें',
    optional: '(वैकल्पिक)',
    unassigned: 'अनिर्दिष्ट',
    selectAssignee: 'असाइनी चुनें',
    assigneeDescription: 'इस दस्तावेज़ को प्रोजेक्ट सदस्य को सौंपें',
    today: 'आज',
    yesterday: 'कल',
    link_a_file: 'फ़ाइल लिंक करें',
    search_files: 'फ़ाइलें खोजें...',
    loading_files: 'फ़ाइलें लोड हो रही हैं...',
    no_files_matching: 'कोई फ़ाइल मेल नहीं खाती',
    go_up: 'ऊपर जाएं',
    folder_is_empty: 'फ़ोल्डर खाली है',
    link: 'लिंक',
    files: 'फ़ाइलें',
    file_details: 'फ़ाइल विवरण',
    uploaded_by: 'द्वारा अपलोड किया गया',
    system_label: 'सिस्टम',
    location_label: 'स्थान',
    downloading_label: 'डाउनलोड हो रहा है...',
    download_file: 'फ़ाइल डाउनलोड करें',
    discussion: 'चर्चा',
    links_label: 'लिंक्स',
    no_linked_items: 'अभी तक कोई लिंक किया गया आइटम नहीं है।',
    view_btn: 'देखें',
    remove_link: 'लिंक हटाएं',
    snag: 'स्नैग',
    view_original: 'मूल देखें',
    zoom_out: 'ज़ूम आउट',
    zoom_in: 'ज़ूम इन',
    rotate: 'घुमाएं',
    exit_fullscreen: 'फ़ुलस्क्रीन से बाहर निकलें',
    fullscreen: 'फ़ुलस्क्रीन',
    preview_not_available: 'इस फ़ाइल प्रकार के लिए पूर्वावलोकन उपलब्ध नहीं है',
    file_linked_success: 'फ़ाइल सफलतापूर्वक लिंक की गई',
    link_rfi: 'फ़ाइल सफलतापूर्वक आरएफआई से लिंक की गई',
    link_snag: 'फ़ाइल सफलतापूर्वक स्नैग से लिंक की गई',
    file_link_failed: 'फ़ाइल को लिंक करने में विफल',
    link_removed_success: 'लिंक सफलतापूर्वक हटाया गया',
    link_remove_failed: 'लिंक हटाने में विफल',

    failed_create_snag: 'स्नैग बनाने में विफल',
    
    failed_delete_photos: 'फ़ोटो हटाने में विफल',
    photo_unarchived_success: 'फ़ोटो को सफलतापूर्वक अनआर्काइव किया गया',
    failed_to_unarchive_photo: 'फ़ोटो अनआर्काइव करने में विफल',

    select_photo_delete: 'कृपया हटाने के लिए कम से कम एक फ़ोटो चुनें',
    protected_folder_delete_error: 'सिस्टम फ़ोल्डर (आर्काइव/कन्फर्मेशन) में मौजूद फ़ाइलें नहीं हटाई जा सकतीं।',
    unauthorized_delete_error: 'आप केवल वही फ़ोटो हटा सकते हैं जिन्हें आपने मूल रूप से अपलोड किया था।',
    confirm_delete_multiple_photos: 'क्या इन {count} फ़ोटो को ट्रैश में ले जाना है? इन्हें 30 दिनों के लिए सेटिंग्स से रिकवर किया जा सकता है।',
    photos_deleted_msg: 'चयनित फ़ोटो सफलतापूर्वक हटा दी गईं',

    unarchive_photo_tip: 'फ़ोटो अनआर्काइव करें',
   
    create_snag_photo_title: 'फ़ोटो से स्नैग बनाएं',
    create_snag_photo_desc: 'इस फ़ोटो से जुड़ा एक नया स्नैग बनाएं। नीचे दिए गए विवरण भरें।',
    
    enter_snag_title: 'स्नैग का शीर्षक दर्ज करें',
    
    enter_snag_desc: 'स्नैग का विवरण दर्ज करें',
    assignee_label: 'असाइनी',
    select_assignee: 'असाइनी चुनें',
    creating_btn: 'बनाया जा रहा है...',
    create_snag_btn: 'स्नैग बनाएं',
    create_rfi_photo_title: 'फ़ोटो से RFI बनाएं',
    create_rfi_photo_desc: 'इस फ़ोटो से जुड़ा एक नया RFI बनाएं। नीचे दिए गए विवरण भरें।',
    enter_rfi_title: 'RFI का शीर्षक दर्ज करें',
    enter_rfi_desc: 'RFI का विवरण दर्ज करें',
    
    create_rfi: 'RFI बनाएं',
    create_snag: 'स्नैग बनाएं',
    confirmations_folder_name: 'Confirmations',
    'projectSnags.viewLinkedAttachments': 'लिंक किए गए अनुलग्नक देखें',
    'projectRfi.viewLinkedAttachments': 'लिंक किए गए अनुलग्नक देखें',
    rename_btn: 'नाम बदलें',
    rename_file_title: 'फ़ाइल का नाम बदलें',
    rename_folder_title: 'फ़ोल्डर का नाम बदलें',
    new_name_label: 'नया नाम',
    enter_new_name_placeholder: 'नया फ़ाइल नाम दर्ज करें',
    renaming_btn: 'नाम बदला जा रहा है...',
    upload_new_version: 'नया संस्करण अपलोड करें',
    version_promoted_success: 'संस्करण को वर्तमान सक्रिय संस्करण में प्रोमोट किया गया',
    confirm_delete_version: 'क्या आप वाकई इस संस्करण को हटाना चाहते हैं?',
    version_deleted_success: 'संस्करण सफलतापूर्वक हटा दिया गया',
    versions: 'संस्करण',
    loading_versions: 'संस्करण लोड हो रहे हैं...',
    no_versions: 'कोई संस्करण नहीं मिला',
    current_version: 'सक्रिय',
    make_active: 'सक्रिय करें',
  },
  te: {
    welcome_back: 'తిరిగి స్వాగతం',
    hi: 'హాయ్',
    dashboard: 'డ్యాష్‌బోర్డ్',
    upload: 'అప్‌లోడ్',
    activity: 'కార్యాచరణ',
    profile: 'ప్రొఫైల్',
    snag_list: 'స్నాగ్ జాబితా',
    user_mgmt: 'వినియోగదారు నిర్వహణ',
    billing: 'ప్లాన్/అప్‌గ్రేడ్',
    projects: 'ప్రాజెక్ట్‌లు',
    documents: 'పత్రాలు',
    photos: 'ఫోటోలు',
    sign_in: 'సైన్ ఇన్',
    sign_up: 'సైన్ అప్',
    sign_out: 'సైన్ అవుట్',
    settings: 'సెట్టింగ్‌లు',
    analytics: 'అనలిటిక్స్',
    notifications_label: 'నోటిఫికేషన్లు',
    chats: 'చాట్స్',
    teams: 'టీమ్స్',
    org_users: 'సంస్థ వినియోగదారులు',
    all_projects: 'అన్ని ప్రాజెక్ట్‌లు',
    organization_projects: 'సంస్థ ప్రాజెక్ట్‌లు',
    all_organizations: 'అన్ని సంస్థలు',
    create_project: 'ప్రాజెక్ట్ సృష్టించండి',
    search: 'వెతకండి',
    notifications: 'నోటిఫికేషన్లు',
    help_support: 'సహాయం & మద్దతు',
    feedback: 'అభిప్రాయం',
    your_projects: 'మీ ప్రాజెక్ట్‌లు',
    total_projects: 'మొత్తం ప్రాజెక్ట్‌లు',
    manage_projects: 'మీ అన్ని కంపెనీ ప్రాజెక్ట్‌లను నిర్వహించండి',
    assigned_projects: 'మీ కేటాయించిన ప్రాజెక్ట్‌లను చూడండి',
    shared_projects: 'మీ షేర్ చేసిన ప్రాజెక్ట్ ఫైల్‌లను యాక్సెస్ చేయండి',
    no_projects: 'ప్రాజెక్ట్‌లు అందుబాటులో లేవు',
    language: 'భాష',
    english: 'ఆంగ్లం',
    hindi: 'హిందీ',
    telugu: 'తెలుగు',
    choose_plan: 'ప్లాన్ ఎంచుకోండి',
    recommended: 'సిఫార్సు చేయబడింది',
    standard: 'స్టాండర్డ్',
    intermediate: 'ఇంటర్మీడియట్',
    pro: 'ప్రో',
    project_overview: 'ప్రాజెక్ట్ అవలోకనం',
    back_to_projects: 'ప్రాజెక్ట్‌లకు తిరిగి వెళ్ళు',
    daily_reports: 'రోజువారీ నివేదికలు',
    weekly_reports: 'వారపు నివేదికలు',
    manuals: 'చెక్‌లిస్ట్',
    project_not_found: 'ప్రాజెక్ట్ కనుగొనబడలేదు.',
    back_to_dashboard: 'డ్యాష్‌బోర్డ్‌కు తిరిగి వెళ్ళు',
    name_update_success: 'పేరు విజయవంతంగా నవీకరించబడింది',
    name_update_error: 'పేరును నవీకరించడంలో విఫలమైంది',
    company_settings: 'కంపెనీ సెట్టింగ్‌లు',
    company_name_label: 'కంపెనీ పేరు',
    company_name_placeholder: 'కంపెనీ పేరు నమోదు చేయండి',
    company_name_success: 'కంపెనీ పేరు నవీకరించబడింది',
    company_name_error: 'కంపెనీ పేరును నవీకరించడంలో విఫలమైంది',
    company_logo_success: 'కంపెనీ లోగో నవీకరించబడింది',
    company_logo_error: 'కంపెనీ లోగోను అప్‌లోడ్ చేయడంలో విఫలమైంది',
    tap_change_logo: 'లోగో మార్చడానికి నొక్కండి',
    change_password: 'పాస్‌వర్డ్ మార్చండి',
    current_password: 'ప్రస్తుత పాస్‌వర్డ్',
    new_password: 'కొత్త పాస్‌వర్డ్',
    confirm_password: 'కొత్త పాస్‌వర్డ్‌ను నిర్ధారించండి',
    password_mismatch: 'పాస్‌వర్డ్‌లు సరిపోలడం లేదు',
    password_success: 'పాస్‌వర్డ్ విజయవంతంగా నవీకరించబడింది',
    password_error: 'పాస్‌వర్డ్‌ను నవీకరించడంలో విఫలమైంది',
    update_password: 'పాస్‌వర్డ్ నవీకరించండి',
    trash_management: 'ట్రాష్ మేనేజ్‌మెంట్',
    trash_management_subtitle: 'తొలగించబడిన ప్రాజెక్ట్‌లను పునరుద్ధరించండి లేదా తొలగించండి',
    crop_photo_title: 'ప్రొఫైల్ ఫోటోను క్రాప్ చేయండి',
    save_photo: 'ఫోటోను సేవ్ చేయి',
    profile_pic_success: 'ప్రొఫైల్ చిత్రం విజయవంతంగా నవీకరించబడింది',
    profile_pic_error: 'ప్రొఫైల్ చిత్రాన్ని అప్‌లోడ్ చేయడంలో విఫలమైంది',
    cancel: 'రద్దు చేయి',
    save: 'సేవ్ చేయి',
    trash_title: 'ట్రాష్',
    trash_subtitle: 'తొలగించబడిన ఐటమ్‌లను నిర్వహించి పునరుద్ధరించండి',
    loading_trash: 'ట్రాష్ లోడ్ అవుతోంది...',
    trash_empty: 'ట్రాష్ ఖాళీగా ఉంది',
    trash_empty_desc: 'తొలగించబడిన ఐటమ్‌లు శాశ్వతంగా తీసివేయబడకముందే 30 రోజుల పాటు ఇక్కడ కనిపిస్తాయి.',
    day_left: 'రోజు మిగిలి ఉంది',
    days_left: 'రోజులు మిగిలి ఉన్నాయి',
    no_description: 'వివరణ అందుబాటులో లేదు',
    deleted_at: 'తొలగించబడింది',
    restore: 'పునరుద్ధరించు',
    delete_forever: 'శాశ్వతంగా తొలగించు',
    restore_success: 'ఐటమ్ విజయవంతంగా పునరుద్ధరించబడింది',
    restore_error: 'ఐటమ్‌ను పునరుద్ధరించడంలో విఫలమైంది',
    permanent_delete_success: 'ఐటమ్ శాశ్వతంగా తొలగించబడింది',
    permanent_delete_error: 'ఐటమ్‌ను తొలగించడంలో విఫలమైంది',
    load_trash_error: 'ట్రాష్‌ను లోడ్ చేయడంలో విఫలమైంది',
    permanent_delete_confirm: 'మీకు ఖచ్చితంగా తెలుసా? ఇది ఈ ఐటమ్‌ను శాశ్వతంగా తొలగిస్తుంది. ఇది వెనక్కి తీసుకోబడదు.',
    no_permission: 'ఈ పేజీని చూడటానికి మీకు అనుమతి లేదు.',
    load_users_error: 'వినియోగదారులను లోడ్ చేయడంలో విఫలమైంది',
    invalid_email: 'దయచేసి సరైన ఈమెయిల్ నమోదు చేయండి',
    select_project_role: 'దయచేసి ఈ పాత్ర కోసం ఒక ప్రాజెక్ట్‌ను ఎంచుకోండి',
    invite_success: 'ఆహ్వానం విజయవంతంగా పంపబడింది',
    invite_error: 'ఆహ్వానం పంపడంలో విఫలమైంది',
    remove_access_success: 'ప్రాజెక్ట్ యాక్సెస్ విజయవంతంగా తీసివేయబడింది',
    remove_access_error: 'ప్రాజెక్ట్ యాక్సెస్‌ను తీసివేయడంలో విఫలమైంది',
    link_copied: 'లింక్ క్లిప్‌బోర్డ్‌కు కాపీ చేయబడింది',
    user_mgmt_subtitle: 'సంస్థ సభ్యులు మరియు పాత్రలను నిర్వహించండి.',
    add_member: 'సభ్యుడిని జోడించు',
    email_address: 'ఈమెయిల్ చిరునామా',
    role: 'పాత్ర',
    assign_project: 'ప్రాజెక్ట్‌ను కేటాయించు',
    choose_project: 'ప్రాజెక్ట్‌ను ఎంచుకోండి',
    no_projects_found: 'ప్రాజెక్ట్‌లు ఏవీ కనుగొనబడలేదు',
    invite: 'ఆహ్వానించు',
    project_access_links: 'ప్రాజెక్ట్ యాక్సెస్ లింక్‌లు',
    project_access_links_subtitle: 'అంతర్గత సహకారులు మరియు బాహ్య క్లయింట్‌ల కోసం డైరెక్ట్ లాగిన్ లింక్‌లను రూపొందించండి.',
    select_project_placeholder: 'ఒక ప్రాజెక్ట్‌ను ఎంచుకోండి',
    contributor_access: 'సహకారి యాక్సెస్',
    client_access: 'క్లయింట్ యాక్సెస్',
    copy_link: 'లింక్ కాపీ చేయి',
    copied: 'కాపీ చేయబడింది',
    no_project_selected: 'ఏ ప్రాజెక్ట్ ఎంపిక కాలేదు',
    no_project_selected_subtitle: 'సహకారులు మరియు క్లయింట్‌ల కోసం నేరుగా యాక్సెస్ లింక్‌లను రూపొందించడానికి దయచేసి పైన ఉన్న డ్రాప్‌డౌన్ నుండి ప్రాజెక్ట్‌ను ఎంచుకోండి.',
    member: 'సభ్యుడు',
    status: 'స్థితి',
    joined: 'చేరారు',
    actions: 'చర్యలు',
    invited_user: 'ఆహ్వానించబడిన వినియోగదారు',
    no_contact_info: 'సంప్రదింపు సమాచారం లేదు',
    all_projects_label: '(అన్ని ప్రాజెక్ట్‌లు)',
    no_projects_assigned: 'ప్రాజెక్ట్‌లు ఏవీ కేటాయించబడలేదు',
    verified: 'ధృవీకరించబడింది',
    pending: 'పెండింగ్‌లో ఉంది',
    no_users_found: 'మీ సంస్థలో వినియోగదారులు ఎవరూ కనుగొనబడలేదు.',
    remove_access_title: 'ప్రొజెక్ట్ యాక్సెస్‌ను తీసివేయాలా?',
    remove_access_confirm: 'మీరు {name}ని వారి ప్రాజెక్ట్ యాక్సెస్ నుండి తీసివేయాలనుకుంటున్నారా? వినియోగదారు ఖాతా సంస్థలో ఉంటుంది.',
    remove_access_button: 'యాక్సెస్‌ను తీసివేయి',
    blocked_users: 'బ్లాక్ చేయబడిన వినియోగదారులు',
    active_members: 'క్రియాశీల సభ్యులు',
    unblock: 'అన్‌బ్లాక్ చేయి',
    just_delete: 'కేవలం తొలగించు',
    block_and_delete: 'బ్లాక్ చేసి తొలగించు',
    unblock_success: 'వినియోగదారు విజయవంతంగా అన్‌బ్లాక్ చేయబడ్డారు',
    unblock_error: 'వినియోగదారుని అన్‌బ్లాక్ చేయడంలో విఫలమైంది',
    admin: 'నిర్వాహకుడు',
    contributor: 'సహకారి',
    client: 'క్లయింట్',
    // Billing
    billing_subtitle: 'మీ బృందానికి సరిపోయే ప్లాన్‌ను ఎంచుకోండి',
    monthly: 'నెలవారీ',
    annual: 'వార్షిక',
    save_35: '35% ఆదా చేయండి',
    plans_tab: 'ప్లాన్‌లు',
    usage_tab: 'వినియోగం',
    history_tab: 'చరిత్ర',
    most_popular: 'అత్యంత ప్రజాదరణ పొందినది',
    billed_annually: 'ఏడాదికి బిల్ చేయబడింది',
    incl_gst: '(18% GSTతో కలిపి)',
    processing: 'ప్రాసెసింగ్...',
    current_plan: 'ప్రస్తుత ప్లాన్',
    resource_consumption: 'వనరుల వినియోగం',
    resource_consumption_subtitle: 'మీ సంస్థ యొక్క వనరుల వినియోగం యొక్క వివరణాత్మక విభజన',
    plan_validity: 'ప్లాన్ ప్రామాణికత',
    active_projects: 'క్రియాశీల ప్రాజెక్ట్‌లు',
    cloud_storage: 'క్లౌడ్ స్టోరేజ్',
    team_members: 'బృందం సభ్యులు',
    clients: 'క్లయింట్లు',
    snags: 'స్నాగ్స్ (Snags)',
    rfis: 'RFIs',
    active_status: 'క్రియాశీల',
    no_payment_history: 'చెల్లింపు చరిత్ర ఏదీ కనుగొనబడలేదు.',
    invoice: 'ఇన్‌వాయిస్',
    cycle: 'చక్రం',
    amount: 'మొత్తం',
    date: 'తేదీ',
    action: 'చర్య',
    limit: 'పరిమితి',
    payment_success: 'చెల్లింపు విజయవంతమైంది! మీ ప్లాన్ అప్‌గ్రేడ్ చేయబడింది.',
    payment_failed: 'చెల్లింపు విఫలమైంది',
    payment_error: 'చెల్లింపులో ఏదో తప్పు జరిగింది.',
    payment_sdk_error: 'Razorpay SDK లోడ్ కావడంలో విఫలమైంది. దయచేసి మీ ఇంటర్నెట్ కనెక్షన్‌ని తనిఖీ చేయండి.',
    payment_verification_failed: 'చెల్లింపు ధృవీకరణ విఫలమైంది. దయచేసి మద్దతును సంప్రదించండి.',
    price_custom: 'కస్టమ్',
    // Chats
    access_denied: 'యాక్సెస్ తిరస్కరించబడింది',
    superadmin_chat_no_access: 'సూపర్ అడ్మిన్‌లకు చాట్ ఫీచర్‌కు యాక్సెస్ లేదు.',
    loading_chats: 'చాట్‌లు లోడ్ అవుతున్నాయి...',
    search_chats: 'చాట్‌లను వెతకండి...',
    no_chats_found: 'చాట్‌లు ఏవీ కనుగొనబడలేదు',
    chat_fallback: 'చాట్',
    more_projects: '+{count} మరిన్ని',
    user_is_typing: '{name} టైప్ చేస్తున్నారు...',
    photo: 'ఫోటో',
    file: 'ఫైల్',
    group_chat: 'గ్రూప్ చాట్',
    direct_message: 'డైరెక్ట్ మెసేజ్',
    loading_messages: 'సందేశాలు లోడ్ అవుతున్నాయి...',
    online: 'ఆన్‌లైన్',
    offline: 'ఆఫ్‌లైన్',
    members_count: '{count} సభ్యులు',
    user_fallback: 'వినియోగదారు',
    voice_note: 'వాయిస్ నోట్',
    photo_message: 'ఫోటో',
    file_message: 'ఫైల్',
    message_fallback: 'సందేశం',
    replied_to_message: 'సందేశానికి ప్రత్యుత్తరం ఇచ్చారు',
    message_placeholder: 'సందేశం...',
    new_group: 'కొత్త గ్రూప్',
    new_direct_chat: 'కొత్త డైరెక్ట్ చాట్',
    search_people: 'వ్యక్తులను వెతకండి...',
    group_name_placeholder: 'గ్రూప్ పేరు',
    users_selected: '{count} ఎంపిక చేయబడ్డారు',
    create_group_btn: 'గ్రూప్‌ను సృష్టించండి ({count})',
    create_chat_btn: 'చాట్‌ను సృష్టించండి',
    enter_group_name: 'దయచేసి గ్రూప్ పేరును నమోదు చేయండి',
    failed_create_chat: 'చాట్‌ను సృష్టించడంలో విఫలమైంది',
    all_actions: 'అన్ని చర్యలు',
    snags_label: 'స్నాగ్స్ (Snags)',
    rfi_label: 'RFI',
    members_label: 'సభ్యులు',
    back_to_unread: 'చదవని వాటికి తిరిగి వెళ్ళు',
    history: 'చరిత్ర',
    notifications_subtitle: 'ప్రాజెక్ట్ మార్పులతో అప్‌డేట్‌గా ఉండండి',
    mark_all_read: 'అన్నీ చదివినట్లుగా గుర్తించు',
    all_users: 'అన్ని వినియోగదారులు',
    no_notifications_48h: 'గత 48 గంటల్లో నోటిఫికేషన్లు ఏవీ లేవు',
    no_new_notifications: 'కొత్త నోటిఫికేషన్లు ఏవీ లేవు',
    all_caught_up: 'మీరు అంతా చూసేశారు!',
    activity_subtitle: 'మీ ప్రాజెక్ట్‌ల నుండి అప్‌డేట్‌లు',
    no_recent_activity: 'ఇటీవలి కార్యాచరణ ఏదీ లేదు',
    team_mgmt_hub: 'టీమ్ మేనేజ్‌మెంట్ హబ్',
    filter_access_control: 'ఫిల్టర్ & యాక్సెస్ కంట్రోల్',
    project_access: 'ప్రాజెక్ట్ యాక్సెస్',
    team_role: 'టీమ్ పాత్ర',
    all_roles: 'అన్ని పాత్రలు',
    reset: 'రీసెట్ చేయి',
    copy_contributor_link: 'సహకారి లింక్‌ను కాపీ చేయి',
    copy_client_link: 'క్లయింట్ లింక్‌ను కాపీ చేయి',
    no_users_filter: 'మీ ఫిల్టర్లకు సరిపోయే వినియోగదారులు ఎవరూ కనుగొనబడలేదు.',
    excellent: 'అద్భుతం',
    moderate: 'మితమైన',
    attention_needed: 'శ్రద్ధ అవసరం',
    access_restricted_admins: 'యాక్సెస్ అడ్మిన్‌లకు మాత్రమే పరిమితం చేయబడింది.',
    go_back: 'వెనక్కి వెళ్ళు',
    admin_analytics: 'అడ్మిన్ అనలిటిక్స్',
    analytics_subtitle: 'కంపెనీ వ్యాప్త ప్రాజెక్ట్ ఇంటెలిజెన్స్',
    tasks_pending: 'పెండింగ్‌లో ఉన్న పనులు',
    tasks_overdue: 'గడువు ముగిసిన పనులు',
    delayed_projects: 'ఆలస్యమైన ప్రాజెక్ట్‌లు',
    avg_completion: 'సగటు పూర్తి',
    project_status: 'ప్రాజెక్ట్ స్థితి',
    task_completion_trend: 'పని పూర్తి ధోరణి',
    completed_label: 'పూర్తయింది',
    created_label: 'సృష్టించబడింది',
    communication_activity: 'కమ్యూనికేషన్ కార్యాచరణ',
    messages_week: 'ఈ వారం సందేశాలు',
    project_pulse_score: 'ప్రాజెక్ట్ పల్స్ స్కోర్',
    pulse: 'పల్స్',
    progress: 'ప్రగతి',
    snags_pt: 'స్నాగ్స్ (P/T)',
    rfis_pt: 'RFIs (P/T)',
    risk: 'ప్రమాదం',
    team_leaderboard: 'టీమ్ లీడర్‌బోర్డ్',
    tasks_count: '{count} పనులు',
    avg_label: 'సగటు:',
    live_activity: 'లైవ్ కార్యాచరణ',
    critical_issue_summary: 'క్లిష్టమైన సమస్యల సారాంశం',
    open_snags: 'ఓపెన్ స్నాగ్స్',
    overdue_items: 'గడువు ముగిసిన అంశాలు',
    active_rfis: 'క్రియాశీల RFIs',
    file_uploads_week: 'ఈ వారం ఫైల్ అప్‌లోడ్‌లు',
    sort_by: 'దీని ద్వారా క్రమబద్ధీకరించు:',
    sort_projects_by: 'ప్రాజెక్ట్‌లను దీని ప్రకారం క్రమబద్ధీకరించండి',
    name_label: 'పేరు',
    newest: 'కొత్తవి',
    oldest: 'పాతవి',
    create_new_project: 'కొత్త ప్రాజెక్ట్‌ను సృష్టించండి',
    project_name_max: 'ప్రాజెక్ట్ పేరు (గరిష్టంగా 25)',
    company_client_max: 'కంపెనీ పేరు/క్లయింట్ పేరు (గరిష్టంగా 50)',
    enter_company_client: 'కంపెనీ/క్లయింట్ పేరు నమోదు చేయండి',
    start_date: 'ప్రారంభ తేదీ',
    end_date: 'ముగింపు తేదీ',
    no_company_client: 'కంపెనీ/క్లయింట్ పేరు లేదు',
    contributor_label: 'సహకారి:',
    client_label: 'క్లయింట్:',
    copied_to_clipboard: 'క్లిప్‌బోర్డ్‌కు కాపీ చేయబడింది',
    org_logo_updated: 'సంస్థ లోగో నవీకరించబడింది',
    logo_upload_failed: 'లోగో అప్‌లోడ్ విఫలమైంది',
    project_limit_reached: 'పరిమితి చేరుకుంది: మీరు మీ ప్రాజెక్ట్ పరిమితిని చేరుకున్నారు. మరిన్ని ప్రాజెక్ట్‌లను సృష్టించడానికి దయచేసి మీ ప్లాన్‌ను అప్‌గ్రేడ్ చేయండి.',
    upgrade_label: 'అప్‌గ్రేడ్ చేయండి',
    project_created_success: 'ప్రాజెక్ట్ విజయవంతంగా సృష్టించబడింది',
    project_create_failed: 'ప్రాజెక్ట్‌ను సృష్టించడంలో విఫలమైంది',
    login_to_view_dashboard: 'డ్యాష్‌బోర్డ్‌ను చూడటానికి దయచేసి లాగిన్ చేయండి.',
    logo_placeholder: 'లోగో',
    crop_logo: 'లోగోను క్రాప్ చేయండి',
    upload_logo_btn: 'లోగోను అప్‌లోడ్ చేయండి',
    no_logo: 'లోగో లేదు',
    org_logo_title: 'సంస్థ లోగో',
    logo_represents: 'ఈ లోగో {name}ని సూచిస్తుంది.',
    change_logo: 'లోగో మార్చండి',
    loading_overview: 'ప్రాజెక్ట్ అవలోకనం లోడ్ అవుతోంది...',
    failed_load_members: 'సభ్యులను లోడ్ చేయడంలో విఫలమైంది',
    project_access_removed: 'ప్రాజెక్ట్ యాక్సెస్ తీసివేయబడింది',
    failed_remove_access: 'ప్రాజెక్ట్ యాక్సెస్‌ను తీసివేయడంలో విఫలమైంది',
    export_completed: 'ఎగుమతి {count}సెకన్లలో పూర్తయింది!',
    export_failed: 'ఎగుమతి విఫలమైంది: {error}',
    starting_export: 'ఎగుమతి ప్రక్రియను ప్రారంభిస్తోంది...',
    failed_trigger_export: 'ఎగుమతిని ప్రారంభించడంలో విఫలమైంది',
    failed_share_link: 'షేర్ లింక్‌ను రూపొందించడంలో విఫలమైంది',
    client_project_code: 'క్లయింట్ ప్రాజెక్ట్ కోడ్',
    active_label: 'క్రియాశీల',
    reports_label: 'నివేదికలు',
    files_label: 'ఫైళ్లు',
    view_reports: 'నివేదికలను చూడండి',
    open_issues: 'ఓపెన్ సమస్యలు',
    access_codes: 'యాక్సెస్ కోడ్‌లు',
    contributor_code_label: 'సహకారి కోడ్',
    client_list_label: 'క్లయింట్ జాబితా',
    code_restricted: 'కోడ్ పరిమితం చేయబడింది',
    client_code_label: 'క్లయింట్ కోడ్',
    final_handover_report: 'తుది హ్యాండోవర్ నివేదిక',
    exporting_label: 'ఎగుమతి చేస్తోంది...',
    time_left: '{time} మిగిలి ఉంది',
    report_ready: 'నివేదిక సిద్ధంగా ఉంది',
    generated_label: 'రూపొందించబడింది',
    download_label: 'డౌన్‌లోడ్',
    generate_new_report: 'కొత్త నివేదికను రూపొందించండి',
    export_final_handover: 'తుది హ్యాండోవర్ నివేదికను ఎగుమతి చేయండి',
    no_active_members: 'క్రియాశీల {role} సభ్యులు ఎవరూ కనుగొనబడలేదు',
    primary_label: '(ప్రాథమిక)',
    edit_project: 'ప్రాజెక్ట్‌ను సవరించండి',
    save_changes: 'మార్పులను సేవ్ చేయండి',
    project_updated_success: 'ప్రాజెక్ట్ విజయవంతంగా నవీకరించబడింది',
    project_update_failed: 'ప్రాజెక్ట్‌ను నవీకరించడంలో విఫలమైంది',
    confirm_delete_project: 'మీరు ఖచ్చితంగా ఈ ప్రాజెక్ట్‌ను తొలగించాలనుకుంటున్నారా? ఇది ట్రాష్‌కు తరలించబడుతుంది మరియు తర్వాత మీ ప్రొఫైల్ సెట్టింగ్‌ల నుండి 30 రోజుల పాటు పునరుద్ధరించబడుతుంది.',
    project_moved_trash: 'ప్రాజెక్ట్ ట్రాష్‌కు తరలించబడింది',
    delete_project_failed: 'ప్రాజెక్ట్‌ను తొలగించడంలో విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.',
    deleting_project: 'ప్రాజెక్ట్‌ను తొలగిస్తోంది',
    wait_cleaning_assets: 'మేము అన్ని ఆస్తులను శుభ్రం చేస్తున్నప్పుడు దయచేసి వేచి ఉండండి...',
    doc_marked_visible: 'పత్రం క్లయింట్‌లకు కనిపించేలా గుర్తించబడింది',
    doc_marked_hidden: 'పత్రం క్లయింట్‌ల కోసం దాచబడింది',
    failed_toggle_visibility: 'కనిపించే స్థితిని మార్చడంలో విఫలమైంది',
    doc_marked_dnf: "పత్రం 'ఫాలో అవ్వకండి'గా గుర్తించబడింది",
    doc_unmarked_dnf: "పత్రం 'ఫాలో అవ్వకండి' నుండి తీసివేయబడింది",
    failed_toggle_dnf: 'ఫాలో అవ్వకండి స్థితిని మార్చడంలో విఫలమైంది',
    doc_marked_ofr: "పత్రం 'కేవలం సూచన కోసం'గా గుర్తించబడింది",
    doc_unmarked_ofr: "పత్రం 'కేవలం సూచన కోసం' నుండి తీసివేయబడింది",
    failed_toggle_ofr: 'కేవలం సూచన కోసం స్థితిని మార్చడంలో విఫలమైంది',
    folder_marked_visible: 'ఫోల్డర్ క్లయింట్‌లకు కనిపించేలా గుర్తించబడింది',
    folder_marked_hidden: 'ఫోల్డర్ క్లయింట్‌ల కోసం దాచబడింది',
    archive_confirm_msg: 'మీరు ఖచ్చితంగా ఈ పత్రాన్ని ఆర్కైవ్ చేయాలనుకుంటున్నారా? ఇది ఆర్కైవ్ ఫోల్డర్‌కు తరలించబడుతుంది మరియు "ఫాలో అవ్వకండి"కి సెట్ చేయబడుతుంది.',
    doc_archived: 'పత్రం ఆర్కైవ్ చేయబడింది',
    failed_archive_doc: 'పత్రాన్ని ఆర్కైవ్ చేయడంలో విఫలమైంది',
    archive_name_reserved: "'Archive' పేరు సిస్టమ్ ఉపయోగం కోసం కేటాయించబడింది",
    folder_created_msg: 'ఫోల్డర్ "{name}" రూపొందించబడింది',
    create_folder_title: 'కొత్త ఫోల్డర్ సృష్టించండి',
    folder_name_label: '{type} కోసం ఫోల్డర్ పేరు',
    folder_name_placeholder: 'ఫోల్డర్ పేరు నమోదు చేయండి',
    create_folder_btn: 'ఫోల్డర్‌ను సృష్టించండి',
    failed_create_folder: 'ఫోల్డర్‌ను రూపొందించడంలో విఫలమైంది',
    folder_renamed_msg: 'ఫోల్డర్ పేరు "{name}"గా మార్చబడింది',
    failed_rename_folder: 'ఫోల్డర్ పేరు మార్చడంలో విఫలమైంది',
    file_renamed_msg: 'ఫైల్ పేరు "{name}"గా మార్చబడింది',
    failed_rename_file: 'ఫైల్ పేరు మార్చడంలో విఫలమైంది',
    confirm_delete_folder: '"{name}" ఫోల్డర్‌ను ట్రాష్‌కు పంపాలా? దీన్ని తర్వాత మీ ప్రొఫైల్ సెట్టింగ్‌ల నుండి 30 రోజుల పాటు రికవర్ చేయవచ్చు.',
    folder_deleted_msg: 'ఫోల్డర్ "{name}" తొలగించబడింది',
    failed_delete_folder: 'ఫోల్డర్‌ను తొలగించడంలో విఫలమైంది',
    folder_already_empty: 'ఫోల్డర్ ఇప్పటికే ఖాళీగా ఉంది',
    visibility_updated_msg: '{count} అంశాల కోసం కనిపింపు నవీకరించబడింది',
    dnf_updated_msg: "{count} ఫైల్‌ల కోసం 'ఫాలో అవ్వకండి' నవీకరించబడింది",
    select_file_share: 'భాగస్వామ్యం చేయడానికి కనీసం ఒక ఫైల్‌ను ఎంచుకోండి',
    upload_file_btn: 'ఫైల్‌ను అప్‌లోడ్ చేయండి',
    new_folder_btn: 'కొత్త ఫోల్డర్',
    select_btn: 'ఎంచుకోండి',
    grid_view_tip: 'గ్రిడ్ వీక్షణ',
    list_view_tip: 'జాబితా వీక్షణ',
    sort_by_label: 'ద్వారా క్రమబద్ధీకరించు:',
    sort_docs_title: 'పత్రాలను క్రమబద్ధీకరించండి',
    date_label: 'సవరించిన తేదీ',
    size_label: 'పరిమాణం',
    files_folders_tab: 'ఫైల్‌లు & ఫోల్డర్‌లు',
    linked_rfi_tab: 'లింక్ చేయబడిన RFIలు',
    linked_rfi_and_snag_tab: 'లింక్ చేయబడిన RFIలు & స్నాగ్‌లు',
    move_folder_tip: 'ఫోల్డర్‌ను తరలించండి',
    rename_folder_tip: 'ఫోల్డర్ పేరు మార్చండి',
    files_count_label: '{count} ఫైల్‌లు',
    folder_count_label: '{count} ఫోల్డర్',
    folders_count_label: '{count} ఫోల్డర్‌లు',
    share_link_tip: 'లింక్ ద్వారా భాగస్వామ్యం చేయండి',
    rename_file_tip: 'ఫైల్ పేరు మార్చండి',
    toggle_visibility_tip: 'కనిపింపును మార్చండి',
    toggle_dnf_tip: 'ఫాలో అవ్వకండి మార్చండి',
    move_file_tip: 'ఫైల్‌ను తరలించండి',
    archive_file_tip: 'ఫైల్‌ను ఆర్కైవ్ చేయండి',
    dnf_tag: 'DNF',
    do_not_follow_tag: 'ఫాలో అవ్వకండి',
    toggle_ofr_tip: 'కేవలం సూచన కోసం మార్చండి',
    ofr_tag: 'OFR',
    only_for_reference_tag: 'కేవలం సూచన కోసం',
    toggle_client_vis_tip: 'క్లయింట్ కనిపింపును మార్చండి',
    no_docs_yet: 'ఇంకా ఫోల్డర్‌లు లేదా పత్రాలు లేవు',
    items_selected: '{count} ఎంచుకోబడ్డాయి',
    share_btn: 'భాగస్వామ్యం చేయండి',
    move_btn: 'తరలించండి',
    show_btn: 'చూపండి',
    hide_btn: 'దాచండి',
    regular_btn: 'సాధారణ',
    clear_selection_tip: 'ఎంపికను క్లియర్ చేయండి',
    folder_deleted_move_msg: 'విషయాలను తరలించిన తర్వాత ఫోల్డర్ "{name}" తొలగించబడింది',
    failed_delete_empty_folder: 'విషయాలు తరలించబడ్డాయి, కానీ ఖాళీ ఫోల్డర్‌ను తొలగించడంలో విఫలమైంది',
    folder_not_empty_title: 'ఫోల్డర్ ఖాళీగా లేదు',
    folder_not_empty_desc: 'ఫోల్డర్ {name} ఫైల్‌లు లేదా ఉప ఫోల్డర్‌లను కలిగి ఉంది. మీరు ఎలా కొనసాగాలనుకుంటున్నారు?',
    delete_everything_btn: 'అన్నీ తొలగించండి',
    delete_everything_desc: 'ఫోల్డర్ మరియు దానిలోని అన్ని విషయాలను శాశ్వతంగా తొలగించండి',
    move_contents_first_btn: 'ముందు విషయాలను తరలించండి',
    move_contents_first_desc: 'లోపల ఉన్న అంశాల కోసం మరొక మార్గాన్ని ఎంచుకోండి',
    photo_marked_visible: 'ఫోటో క్లయింట్‌లకు కనిపించేలా గుర్తించబడింది',
    photo_marked_hidden: 'ఫోటో క్లయింట్‌ల కోసం దాచబడింది',
    photo_marked_dnf: "ఫోటో 'ఫాలో అవ్వకండి'గా గుర్తించబడింది",
    photo_unmarked_dnf: "ఫోటో 'ఫాలో అవ్వకండి' నుండి తీసివేయబడింది",
    confirm_delete_photo: 'ఈ ఫోటోను ట్రాష్‌కు పంపాలా? దీన్ని తర్వాత మీ ప్రొఫైల్ సెట్టింగ్‌ల నుండి 30 రోజుల పాటు రికవర్ చేయవచ్చు.',
    photo_deleted_msg: 'ఫోటో తొలగించబడింది',
    failed_delete_photo: 'ఫోటోను తొలగించడంలో విఫలమైంది',
    select_photo_share: 'భాగస్వామ్యం చేయడానికి కనీసం ఒక ఫోటోను ఎంచుకోండి',
    upload_photo_btn: 'ఫోటోను అప్‌లోడ్ చేయండి',
    sort_photos_title: 'ఫోటోలను క్రమబద్ధీకరించండి',
    photos_folders_tab: 'ఫోటోలు & ఫోల్డర్‌లు',
    delete_folder_tip: 'ఫోల్డర్‌ను తొలగించండి',
    photos_count_label: '{count} ఫోటోలు',
    delete_photo_tip: 'ఫోటోను తొలగించండి',
    no_photos_yet: 'ఇంకా ఫోల్డర్‌లు లేదా ఫోటోలు లేవు',
    daily_label: 'రోజువారీ',
    weekly_label: 'వారపు',
    monthly_label: 'నెలవారీ',
    daily_report: 'రోజువారీ నివేదిక',
    weekly_report: 'వారపు నివేదిక',
    monthly_report: 'నెలవారీ నివేదిక',
    generating_label: 'రూపొందిస్తోంది...',
    generate_report_btn: '{type} నివేదికను రూపొందించండి',
    report_period_to: 'నుండి',
    download_pdf_tip: 'PDF డౌన్‌లోడ్ చేయండి',
    no_detail_records: 'ఈ కాలానికి వివరాల రికార్డులు ఏవీ లేవు',
    docs_uploaded_title: 'పత్రాలు అప్‌లోడ్ చేయబడ్డాయి',
    photos_uploaded_title: 'ఫోటోలు అప్‌లోడ్ చేయబడ్డాయి',
    uploaded_by_in: '({folder}లో {user} ద్వారా)',
    photos_by_in: '{folder}లో {user} ద్వారా {count} ఫోటోలు',
    no_reports_found: '{type} నివేదికలు ఏవీ కనుగొనబడలేదు',
    generate_to_start: 'ప్రారంభించడానికి ఒకదాన్ని రూపొందించండి',
    export_options_title: 'ఎగుమతి ఎంపికలు',
    export_options_subtitle: 'మీ నివేదికలో చేర్చడానికి విభాగాలను ఎంచుకోండి',
    waiting_clearance: 'క్లియరెన్స్ కోసం వేచి ఉంది',
    open_status: 'ఓపెన్',
    completed_status: 'పూర్తయింది',
    resolved_status: 'పరిష్కరించబడింది',
    no_action_required: 'చర్య అవసరం లేదు',
    overdue_status: 'గడువు ముగిసింది',
    project_snags_title: 'ప్రాజెక్ట్ స్నాగ్స్',
    add_snag_btn: 'స్నాగ్‌ను జోడించండి',
    status_label: 'స్థితి',
    all_status: 'అన్ని స్థితిగతులు',
    created_by_label: 'రూపొందించినవారు',
    all_creators: 'నిర్మాతలందరూ',
    assigned_to_label: 'కేటాయించినవారు',
    all_assignees: 'కేటాయించినవారందరూ',
    clear_all_btn: 'అన్నీ క్లియర్ చేయి',
    to_label: 'కు:',
    by_label: 'ద్వారా:',
    seen_badge: 'చూశారు',
    no_snags_found: 'స్నాగ్స్ ఏవీ కనుగొనబడలేదు',
    snag_filter_empty_desc: 'మీ ఫిల్టర్‌లను మార్చడానికి ప్రయత్నించండి లేదా కొత్త స్నాగ్‌ను జోడించండి',
    edit_snag_title: 'స్నాగ్‌ను సవరించండి',
    add_snag_title: 'స్నాగ్‌ను జోడించండి',
    click_attach_photo: 'ఫోటోను జోడించడానికి క్లిక్ చేయండి',
    photo_format_hint: 'అవసరం — JPG, PNG, మొదలైనవి.',
    snag_title_placeholder: 'స్నాగ్ శీర్షిక *',
    description_optional: 'వివరణ (ఐచ్ఛికం)',
    assign_to_placeholder: 'కేటాయించండి... *',
    voice_note_label: 'వాయిస్ నోట్',
    change_btn: 'మార్చు',
    edit_btn: 'సవరించు',
    delete_btn: 'తొలగించు',
    unassigned_label: 'కేటాయించబడలేదు',
    last_response_title: 'చివరి ప్రతిస్పందన',
    voice_response_label: 'వాయిస్ ప్రతిస్పందన',
    update_status_respond_title: 'స్థితిని నవీకరించండి & ప్రతిస్పందించండి',
    add_comment_placeholder: 'ఒక వ్యాఖ్యను జోడించండి...',
    post_response_btn: 'ప్రతిస్పందనను పోస్ట్ చేయండి',
    failed_load_snags: 'స్నాగ్స్‌ను లోడ్ చేయడంలో విఫలమైంది',
    status_updated_to_msg: 'స్థితి {label}కి నవీకరించబడింది',
    failed_update_status: 'స్థితిని నవీకరించడంలో విఫలమైంది',
    select_image_file_msg: 'దయచేసి ఒక చిత్ర ఫైల్‌ను ఎంచుకోండి',
    title_required_msg: 'శీర్షిక అవసరం',
    assignee_required_msg: 'కేటాయించినవారు అవసరం',
    photo_required_msg: 'ఫోటో అవసరం',
    snag_limit_msg: 'పరిమితి చేరుకుంది: మీరు మీ స్నాగ్ పరిమితిని చేరుకున్నారు. మరిన్ని స్నాగ్‌లను జోడించడానికి దయచేసి మీ ప్లాన్‌ను అప్‌గ్రేడ్ చేయండి.',
    snag_added_msg: 'స్నాగ్ జోడించబడింది',
    failed_add_snag: 'స్నాగ్‌ను జోడించడంలో విఫలమైంది',
    snag_updated_msg: 'స్నాగ్ నవీకరించబడింది',
    failed_update_snag: 'స్నాగ్‌ను నవీకరించడంలో విఫలమైంది',
    confirm_delete_snag: '"{title}"ని ట్రాష్‌కు పంపాలా? దీన్ని తర్వాత మీ ప్రొఫైల్ సెట్టింగ్‌ల నుండి 30 రోజుల పాటు రికవర్ చేయవచ్చు.',
    snag_deleted_msg: 'స్నాగ్ తొలగించబడింది',
    failed_delete_snag: 'స్నాగ్‌ను తొలగించడంలో విఫలమైంది',
    only_assignee_update_msg: 'కేటాయించిన వ్యక్తి మాత్రమే స్థితిని నవీకరించగలరు',
    status_click_change_tip: 'స్థితి: {label} — మార్చడానికి క్లిక్ చేయండి',
    status_tip: 'స్థితి: {label}',
    closed_status: 'ముగిసింది',
    request_for_info_title: 'సమాచారం కోసం అభ్యర్థన (RFI)',
    new_rfi_btn: 'కొత్త RFI',
    all_creators_label: 'నిర్మాతలందరూ',
    all_assignees_label: 'కేటాయించినవారందరూ',
    by_user_label: '{name} ద్వారా',
    assigned_to_user_label: '{name}కు కేటాయించబడింది',
    attachments_count_label: '{count} జోడింపులు',
    no_rfis_found: 'సమాచారం కోసం అభ్యర్థనలేవీ కనుగొనబడలేదు',
    rfi_filter_empty_desc: 'మీ ఫిల్టర్‌లను మార్చడానికి ప్రయత్నించండి లేదా కొత్త RFIని సృష్టించండి',
    edit_rfi_title: 'సమాచారం కోసం అభ్యర్థనను సవరించండి',
    new_rfi_title: 'సమాచారం కోసం కొత్త అభ్యర్థన',
    title_label: 'శీర్షిక *',
    rfi_title_placeholder: 'RFI శీర్షికను నమోదు చేయండి',
    description_label: 'వివరణ',
    rfi_context_placeholder: 'మరింత సమాచారాన్ని అందించండి...',
    assign_to_label: 'కేటాయించండి *',
    select_assignee_placeholder: 'కేటాయించినవారిని ఎంచుకోండి *',
    expiry_date_label: 'గడువు తేదీ',
    attachments_label: 'జోడింపులు',
    create_rfi_btn: 'RFIని సృష్టించండి',
    rfi_id_label: 'RFI #{id}',
    link_btn: 'లింక్',
    linked_folders_title: 'లింక్ చేయబడిన ఫోల్డర్‌లు',
    voice_attachment_label: 'వాయిస్ జోడింపు',
    response_title: 'ప్రతిస్పందన',
    update_response_title: 'ప్రతిస్పందనను నవీకరించండి',
    provide_response_title: 'ప్రతిస్పందనను అందించండి',
    rfi_response_placeholder: 'మీ ప్రతిస్పందనను ఇక్కడ టైప్ చేయండి...',
    response_attachments_label: 'ప్రతిస్పందన జోడింపులు',
    submit_response_btn: 'ప్రతిస్పందనను సమర్పించండి',
    update_status_title: 'స్థితిని నవీకరించండి',
    failed_load_rfis: 'RFIలను లోడ్ చేయడంలో విఫలమైంది',
    rfi_limit_msg: 'పరిమితి చేరుకుంది: మీరు మీ RFI పరిమితిని చేరుకున్నారు. మరిన్ని RFIలను సృష్టించడానికి దయచేసి మీ ప్లాన్‌ను అప్‌గ్రేడ్ చేయండి.',
    rfi_created_msg: 'RFI విజయవంతంగా సృష్టించబడింది',
    failed_create_rfi: 'RFIని సృష్టించడంలో విఫలమైంది',
    links_updated_msg: 'లింక్‌లు విజయవంతంగా నవీకరించబడ్డాయి',
    failed_update_links: 'లింక్‌లను నవీకరించడంలో విఫలమైంది',
    rfi_updated_msg: 'RFI విజయవంతంగా నవీకరించబడింది',
    failed_update_rfi: 'RFIని నవీకరించడంలో విఫలమైంది',
    confirm_delete_rfi: 'ఈ RFIని ట్రాష్‌కు పంపాలా? దీన్ని తర్వాత మీ ప్రొఫైల్ సెట్టింగ్‌ల నుండి 30 రోజుల పాటు రికవర్ చేయవచ్చు.',
    rfi_deleted_msg: 'RFI తొలగించబడింది',
    failed_delete_rfi: 'RFIని తొలగించడంలో విఫలమైంది',
    response_updated_msg: 'ప్రతిస్పందన నవీకరించబడింది',
    failed_update_response: 'ప్రతిస్పందనను నవీకరించడంలో విఫలమైంది',
    some_files_skipped_msg: 'కొన్ని ఫైల్‌లు విస్మరించబడ్డాయి (చిత్రాలు కావు)',
    max_4_photos_msg: 'గరిష్టంగా 4 ఫోటోలు మాత్రమే అనుమతించబడతాయి',
    low: 'తక్కువ',
    medium: 'మధ్యస్థం',
    high: 'ఎక్కువ',
    // Features
    feat_single_proj: 'సింగిల్ ప్రాజెక్ట్ యాక్సెస్',
    feat_up_to_5: '5 ప్రాజెక్ట్‌ల వరకు',
    feat_up_to_10: '10 ప్రాజెక్ట్‌ల వరకు',
    feat_above_10: '10 కంటే ఎక్కువ ప్రాజెక్ట్‌లు',
    feat_client_view: 'క్లయింట్ వీక్షించడం',
    feat_basic_report: 'ప్రాథమిక నివేదికలు',
    feat_struct_report: 'నిర్మాణాత్మక నివేదికలు',
    feat_ai_report: 'AI-సహాయక నివేదికలు',
    feat_5gb: '5GB క్లౌడ్ స్టోరేజ్',
    feat_25gb: '25GB క్లౌడ్ స్టోరేజ్',
    feat_100gb: '100GB క్లౌడ్ స్టోరేజ్',
    feat_above_100gb: '100GB కంటే ఎక్కువ క్లౌడ్ స్టోరేజ్',
    feat_onetime: 'ఒకసారి కొనుగోలు',
    feat_basic_dash: 'ప్రాథమిక ప్రాజెక్ట్ డాష్‌బోర్డ్',
    feat_role_access: 'పాత్ర-ఆధారిత యాక్సెస్',
    feat_media_doc: 'మీడియా డాక్యుమెంటేషన్',
    feat_priority_supp: 'ప్రాధాన్యత మద్దతు',
    feat_custom_wf: 'కస్టమ్ వర్క్‌ఫ్లోస్',
    feat_custom_onboard: 'కస్టమ్ ఆన్‌బోర్డింగ్',
    feat_dedic_supp: 'ప్రత్యేక మద్దతు',
    feat_custom_integ: 'కస్టమ్ ఇంటిగ్రేషన్స్',
    feat_snag: 'స్నాగ్ లిస్ట్ ఫీచర్',
    feat_drawings: 'సైట్‌కు డ్రాయింగ్ల విడుదల',
    feat_multilingual: 'బహుభాషా మద్దతు (ఇంగ్లీష్, హిందీ & తెలుగు)',
    feat_secure: 'సురక్షిత డేటా నిల్వ',
    sub_onetime: 'సింగిల్ ప్రాజెక్ట్ యాక్సెస్',
    sub_starter: '5 ప్రాజెక్ట్‌ల వరకు',
    sub_pro: '10 ప్రాజెక్ట్‌ల వరకు',
    sub_enterprise: '10 కంటే ఎక్కువ ప్రాజెక్ట్‌లు',
    validity_90: '90 రోజుల పాటు చెల్లుబాటు అవుతుంది',
    free_trial_14: '14 రోజుల ఉచిత ట్రయల్',
    buy_now: 'ఇప్పుడే కొనండి',
    get_started: 'ప్రారంభించండి',
    upgrade_pro: 'ప్రోకి అప్‌గ్రేడ్ చేయండి',
    contact_sales: 'సేల్స్ టీమ్‌ని సంప్రదించండి',
    failed_load_reports: '{type} నివేదికను లోడ్ చేయడంలో విఫలమైంది',
    manual_label: 'మాన్యువల్',
    checklist_label: 'చెక్ లిస్ట్',
    failed_load_manuals: 'మాన్యువల్‌లను లోడ్ చేయడంలో విఫలమైంది',
    uploaded_successfully: 'విజయవంతంగా అప్‌లోడ్ చేయబడింది',
    upload_failed: 'అప్‌లోడ్ విఫలమైంది',
    confirm_remove_manual: '"{name}"ని ట్రాష్‌కు పంపాలా? దీన్ని తర్వాత మీ ప్రొఫైల్ సెట్టింగ్‌ల నుండి 30 రోజుల పాటు రికవర్ చేయవచ్చు.',
    removed_msg: 'తీసివేయబడింది',
    delete_failed: 'తొలగింపు విఫలమైంది',
    link_copied_msg: 'లింక్ క్లిప్‌బోర్డ్‌కు కాపీ చేయబడింది',
    upload_manual_checklist_btn: 'మాన్యువల్ / చెక్ లిస్ట్ అప్‌లోడ్ చేయండి',
    type_label: 'రకం',
    click_select_file_hint: 'PDF / Word / Excel ఎంచుకోవడానికి క్లిక్ చేయండి',
    max_size_hint: 'గరిష్ట పరిమాణం: 100 MB',
    upload_btn: 'అప్‌లోడ్',
    copy_link_tip: 'లింక్‌ను కాపీ చేయండి',
    no_manuals_yet: 'ఇంకా మాన్యువల్‌లు లేదా చెక్ లిస్ట్‌లు లేవు',
    assign_to: 'కేటాయించండి',
    optional: '(ఐచ్ఛికం)',
    unassigned: 'అన్అసైన్ చేయబడింది',
    selectAssignee: 'అసైన్ చేసిన వ్యక్తిని ఎంచుకోండి',
    assigneeDescription: 'ఈ పత్రాన్ని ప్రాజెక్ట్ సభ్యునికి కేటాయించండి',
    today: 'ఈరోజు',
    yesterday: 'నిన్న',
    link_a_file: 'ఫైల్‌ను లింక్ చేయండి',
    search_files: 'ఫైళ్లను శోధించండి...',
    loading_files: 'ఫైల్‌లు లోడ్ అవుతున్నాయి...',
    no_files_matching: 'సరిపోలే ఫైల్‌లు లేవు',
    go_up: 'పైకి వెళ్ళండి',
    folder_is_empty: 'ఫోల్డర్ ఖాళీగా ఉంది',
    link: 'లింక్',
    files: 'ఫైళ్లు',
    file_details: 'ఫైల్ వివరాలు',
    uploaded_by: 'అప్‌లోడ్ చేసిన వారు',
    system_label: 'సిస్టమ్',
    location_label: 'స్థానం',
    downloading_label: 'డౌన్‌లోడ్ అవుతోంది...',
    download_file: 'ఫైల్‌ను డౌన్‌లోడ్ చేయండి',
    discussion: 'చర్చ',
    links_label: 'లింక్‌లు',
    no_linked_items: 'ఇంకా లింక్ చేయబడిన అంశాలు లేవు.',
    view_btn: 'వీక్షించండి',
    remove_link: 'లింక్‌ను తీసివేయండి',
    snag: 'స్నాగ్',
    view_original: 'అసలు వీక్షించండి',
    zoom_out: 'జూమ్ అవుట్',
    zoom_in: 'జూమ్ ఇన్',
    rotate: 'తిప్పండి',
    exit_fullscreen: 'పూర్తి స్క్రీన్ నుండి నిష్క్రమించండి',
    fullscreen: 'పూర్తి స్క్రీన్',
    preview_not_available: 'ఈ ఫైల్ రకానికి ప్రివ్యూ అందుబాటులో లేదు',
    file_linked_success: 'ఫైల్ విజయవంతంగా లింక్ చేయబడింది',
    link_rfi: 'ఫైల్ విజయవంతంగా RFI కి లింక్ చేయబడింది',
    link_snag: 'ఫైల్ విజయవంతంగా స్నాగ్‌కి లింక్ చేయబడింది',
    file_link_failed: 'ఫైల్‌ను లింక్ చేయడంలో విఫలమైంది',
    link_removed_success: 'లింక్ విజయవంతంగా తీసివేయబడింది',
    link_remove_failed: 'లింక్‌ను తీసివేయడంలో విఫలమైంది',
    
    failed_delete_photos: 'ఫోటోలను తొలగించడంలో విఫలమైంది',
    photo_unarchived_success: 'ఫోటో విజయవంతంగా అన్‌ఆర్కైవ్ చేయబడింది',
    failed_to_unarchive_photo: 'ఫోటోను అన్‌ఆర్కైవ్ చేయడంలో విఫలమైంది',
    select_photo_delete: 'తొలగించడానికి దయచేసి కనీసం ఒక ఫోటోను ఎంచుకోండి',
    protected_folder_delete_error: 'సిస్టమ్ ఫోల్డర్‌లలోని (ఆర్కైవ్/కన్ఫర్మేషన్స్) ఫైల్‌లను తొలగించలేము.',
    unauthorized_delete_error: 'మీరు అప్‌లోడ్ చేసిన ఫోటోలను మాత్రమే తొలగించగలరు.',
    confirm_delete_multiple_photos: 'ఈ {count} ఫోటోలను ట్రాష్‌కు తరలించాలా? వాటిని సెట్టింగ్‌ల నుండి 30 రోజుల పాటు రికవర్ చేయవచ్చు.',
    photos_deleted_msg: 'ఎంచుకున్న ఫోటోలు విజయవంతంగా తొలగించబడ్డాయి',
    unarchive_photo_tip: 'ఫోటో అన్‌ఆర్కైవ్ చేయండి',
    create_snag_photo_title: 'ఫోటో నుండి స్నాగ్ సృష్టించండి',
    create_snag_photo_desc: 'ఈ ఫోటోకు లింక్ చేయబడిన కొత్త స్నాగ్‌ను సృష్టించండి. దిగువ వివరాలను పూరించండి.',
    enter_snag_title: 'స్నాగ్ శీర్షికను నమోదు చేయండి',
    enter_snag_desc: 'స్నాగ్ వివరణను నమోదు చేయండి',
    assignee_label: 'అసైన్ చేయబడిన వారు',
    select_assignee: 'అసైన్ చేయబడిన వారిని ఎంచుకోండి',
    creating_btn: 'సృష్టిస్తోంది...',
    create_snag_btn: 'స్నాగ్ సృష్టించండి',
    create_rfi_photo_title: 'ఫోటో నుండి RFI సృష్టించండి',
    create_rfi_photo_desc: 'ఈ ఫోటోకు లింక్ చేయబడిన కొత్త RFI సృష్టించండి. దిగువ వివరాలను పూరించండి.',
    enter_rfi_title: 'RFI శీర్షికను నమోదు చేయండి',
    enter_rfi_desc: 'RFI వివరణను నమోదు చేయండి',
    create_rfi: 'RFI సృష్టించండి',
    create_snag: 'స్నాగ్ సృష్టించండి',
    confirmations_folder_name: 'Confirmations',
    'projectSnags.viewLinkedAttachments': 'లింక్ చేయబడిన జోడింపులను వీక్షించండి',
    'projectRfi.viewLinkedAttachments': 'లింక్ చేయబడిన జోడింపులను వీక్షించండి',
    rename_btn: 'పేరు మార్చు',
    rename_file_title: 'ఫైల్ పేరు మార్చండి',
    rename_folder_title: 'ఫోల్డర్ పేరు మార్చండి',
    new_name_label: 'కొత్త పేరు',
    enter_new_name_placeholder: 'కొత్త ఫైల్ పేరును నమోదు చేయండి',
    renaming_btn: 'పేరు మారుస్తోంది...',
    upload_new_version: 'కొత్త సంస్కరణను అప్‌లోడ్ చేయండి',
    version_promoted_success: 'సంస్కరణ ప్రస్తుత సక్రియ సంస్కరణకు ప్రమోట్ చేయబడింది',
    confirm_delete_version: 'మీరు ఖచ్చితంగా ఈ సంస్కరణను తొలగించాలనుకుంటున్నారా?',
    version_deleted_success: 'సంస్కరణ విజయవంతంగా తొలగించబడింది',
    versions: 'సంస్కరణలు',
    loading_versions: 'సంస్కరణలు లోడ్ అవుతున్నాయి...',
    no_versions: 'సంస్కరణలు ఏవీ కనుగొనబడలేదు',
    current_version: 'యాక్టివ్',
    make_active: 'యాక్టివ్ చేయి',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => { },
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      return (localStorage.getItem('apexis-lang') as Language) || 'en';
    }
    return 'en';
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('apexis-lang', lang);
  }, []);

  const t = useCallback((key: string) => {
    return translations[language][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
