"use client";

import React, { createContext, useContext, useState, useCallback } from 'react';

export type Language = 'en' | 'hi' | 'te';

const translations: Record<Language, Record<string, string>> = {
  en: {
    welcome_back: 'Welcome back',
    hi: 'Hi',
    dashboard: 'Dashboard',
    upload: 'Upload',
    activity: 'Activity',
    profile: 'Profile',
    snag_list: 'Snag List',
    user_mgmt: 'User Mgmt',
    billing: 'Plan/Upgrade',
    projects: 'Projects',
    documents: 'Documents',
    photos: 'Photos',
    sign_in: 'Sign In',
    sign_up: 'Sign Up',
    sign_out: 'Sign Out',
    settings: 'Settings',
    analytics: 'Analytics',
    notifications_label: 'Notifications',
    chats: 'Chats',
    teams: 'Teams',
    org_users: 'Org Users',
    all_projects: 'All Projects',
    organization_projects: 'Organization Projects',
    all_organizations: 'All Organizations',
    create_project: 'Create Project',
    search: 'Search',
    notifications: 'Notifications',
    help_support: 'Help & Support',
    feedback: 'Feedback',
    your_projects: 'Your Projects',
    total_projects: 'Total Projects',
    manage_projects: 'Manage all your company projects',
    assigned_projects: 'View and contribute to your assigned projects',
    shared_projects: 'Access your shared project files',
    no_projects: 'No projects available',
    language: 'Language',
    english: 'English',
    hindi: 'Hindi',
    telugu: 'Telugu',
    choose_plan: 'Choose Plan',
    recommended: 'Recommended',
    standard: 'Standard',
    intermediate: 'Intermediate',
    pro: 'Pro',
    project_overview: 'Project Overview',
    back_to_projects: 'Back to Projects',
    daily_reports: 'Daily Reports',
    weekly_reports: 'Weekly Reports',
    manuals: 'Checklists',
    project_not_found: 'Project not found.',
    back_to_dashboard: 'Back to Dashboard',
    name_update_success: 'Name updated successfully',
    name_update_error: 'Failed to update name',
    company_settings: 'Company Settings',
    company_name_label: 'Company Name',
    company_name_placeholder: 'Enter company name',
    company_name_success: 'Company name updated',
    company_name_error: 'Failed to update company name',
    company_logo_success: 'Company logo updated',
    company_logo_error: 'Failed to upload company logo',
    tap_change_logo: 'Tap to change logo',
    change_password: 'Change Password',
    current_password: 'Current Password',
    new_password: 'New Password',
    confirm_password: 'Confirm New Password',
    password_mismatch: 'Passwords do not match',
    password_success: 'Password updated successfully',
    password_error: 'Failed to update password',
    update_password: 'Update Password',
    trash_management: 'Trash Management',
    trash_management_subtitle: 'Recover or purge deleted projects',
    crop_photo_title: 'Crop Profile Photo',
    save_photo: 'Save Photo',
    profile_pic_success: 'Profile picture updated successfully',
    profile_pic_error: 'Failed to upload profile picture',
    cancel: 'Cancel',
    save: 'Save',
    trash_title: 'Trash',
    trash_subtitle: 'Manage and restore deleted projects',
    loading_trash: 'Loading trash...',
    trash_empty: 'Trash is Empty',
    trash_empty_desc: 'Deleted projects will appear here for 30 days before being permanently removed.',
    day_left: 'DAY LEFT',
    days_left: 'DAYS LEFT',
    no_description: 'No description available',
    deleted_at: 'Deleted',
    restore: 'Restore',
    delete_forever: 'Delete Forever',
    restore_success: 'Project restored successfully',
    restore_error: 'Failed to restore project',
    permanent_delete_success: 'Project permanently deleted',
    permanent_delete_error: 'Failed to delete project',
    load_trash_error: 'Failed to load trash',
    permanent_delete_confirm: 'Are you sure? This will permanently delete ALL project data. This cannot be undone.',
    no_permission: 'You do not have permission to view this page.',
    load_users_error: 'Failed to load users',
    invalid_email: 'Please enter a valid email',
    select_project_role: 'Please select a project for this role',
    invite_success: 'Invitation sent successfully',
    invite_error: 'Failed to send invitation',
    remove_access_success: 'Project access removed successfully',
    remove_access_error: 'Failed to remove project access',
    link_copied: 'link copied to clipboard',
    user_mgmt_subtitle: 'Manage organization members and roles.',
    add_member: 'Add Member',
    email_address: 'Email Address',
    role: 'Role',
    assign_project: 'Assign Project',
    choose_project: 'Choose Project',
    no_projects_found: 'No projects found',
    invite: 'Invite',
    project_access_links: 'Project Access Links',
    project_access_links_subtitle: 'Generate direct login links for internal contributors and external clients.',
    select_project_placeholder: 'Select a Project',
    contributor_access: 'Contributor Access',
    client_access: 'Client Access',
    copy_link: 'Copy Link',
    copied: 'Copied',
    no_project_selected: 'No Project Selected',
    no_project_selected_subtitle: 'Please select a project from the dropdown above to generate direct access links for contributors and clients.',
    member: 'Member',
    status: 'Status',
    joined: 'Joined',
    actions: 'Actions',
    invited_user: 'Invited User',
    no_contact_info: 'No contact info',
    all_projects_label: '(All Projects)',
    no_projects_assigned: 'No projects assigned',
    verified: 'Verified',
    pending: 'Pending',
    no_users_found: 'No users found in your organization.',
    remove_access_title: 'Remove Project Access?',
    remove_access_confirm: 'Are you sure you want to remove {name} from their project access? The user account will stay in the organization.',
    remove_access_button: 'Remove Access',
    admin: 'Admin',
    contributor: 'Contributor',
    client: 'Client',
    // Billing
    billing_subtitle: 'Choose the plan that fits your team',
    monthly: 'Monthly',
    annual: 'Annual',
    save_35: 'Save 35%',
    plans_tab: 'Plans',
    usage_tab: 'Usage',
    history_tab: 'History',
    most_popular: 'Most Popular',
    billed_annually: 'Billed annually',
    incl_gst: '(Incl. 18% GST)',
    processing: 'Processing...',
    current_plan: 'Current Plan',
    resource_consumption: 'Resource Consumption',
    resource_consumption_subtitle: 'Detailed breakdown of your organization\'s resource usage',
    plan_validity: 'Plan Validity',
    active_projects: 'Active Projects',
    cloud_storage: 'Cloud Storage',
    team_members: 'Team Members',
    clients: 'Clients',
    snags: 'Snags',
    rfis: 'RFIs',
    active_status: 'Active',
    no_payment_history: 'No payment history found.',
    invoice: 'Invoice',
    cycle: 'Cycle',
    amount: 'Amount',
    date: 'Date',
    action: 'Action',
    limit: 'Limit',
    payment_success: 'Payment successful! Your plan has been upgraded.',
    payment_failed: 'Payment failed',
    payment_error: 'Something went wrong with the payment.',
    payment_sdk_error: 'Razorpay SDK failed to load. Please check your internet connection.',
    payment_verification_failed: 'Payment verification failed. Please contact support.',
    price_custom: 'Custom',
    // Chats
    access_denied: 'Access Denied',
    superadmin_chat_no_access: 'Superadmins do not have access to the chat feature.',
    loading_chats: 'Loading chats...',
    search_chats: 'Search chats...',
    no_chats_found: 'No chats found',
    chat_fallback: 'Chat',
    more_projects: '+{count} more',
    user_is_typing: '{name} is typing...',
    photo: 'Photo',
    file: 'File',
    group_chat: 'Group Chat',
    direct_message: 'Direct Message',
    loading_messages: 'Loading messages...',
    online: 'Online',
    offline: 'Offline',
    members_count: '{count} members',
    user_fallback: 'User',
    voice_note: 'Voice Note',
    photo_message: 'Photo',
    file_message: 'File',
    message_fallback: 'Message',
    replied_to_message: 'Replied to message',
    message_placeholder: 'Message...',
    new_group: 'New Group',
    new_direct_chat: 'New Direct Chat',
    search_people: 'Search people...',
    group_name_placeholder: 'Group Name',
    users_selected: '{count} selected',
    create_group_btn: 'Create Group ({count})',
    create_chat_btn: 'Create Chat',
    enter_group_name: 'Please enter a group name',
    failed_create_chat: 'Failed to create chat',
    all_actions: 'All Actions',
    snags_label: 'Snags',
    rfi_label: 'RFI',
    members_label: 'Members',
    back_to_unread: 'Back to unread',
    history: 'History',
    notifications_subtitle: 'Stay updated with project changes',
    mark_all_read: 'Mark all as read',
    all_users: 'All Users',
    no_notifications_48h: 'No notifications in the last 48 hours',
    no_new_notifications: 'No new notifications',
    all_caught_up: 'You\'re all caught up!',
    activity_subtitle: 'Updates from your projects',
    no_recent_activity: 'No recent activity',
    // Features
    feat_single_proj: 'Single Project Access',
    feat_up_to_5: 'Up to 5 Projects',
    feat_up_to_10: 'Up to 10 Projects',
    feat_above_10: 'Above 10 Projects',
    feat_client_view: 'Client Viewership',
    feat_basic_report: 'Basic Reporting',
    feat_struct_report: 'Structured Reporting',
    feat_ai_report: 'AI-Assisted Reports',
    feat_5gb: '5GB Cloud Storage',
    feat_25gb: '25GB Cloud Storage',
    feat_100gb: '100GB Cloud Storage',
    feat_above_100gb: 'Above 100GB Cloud Storage',
    feat_onetime: 'One-time purchase',
    feat_basic_dash: 'Basic Project Dashboard',
    feat_role_access: 'Role-Based Access',
    feat_media_doc: 'Media Documentation',
    feat_priority_supp: 'Priority Support',
    feat_custom_wf: 'Custom Workflows',
    feat_custom_onboard: 'Custom Onboarding',
    feat_dedic_supp: 'Dedicated Support',
    feat_custom_integ: 'Custom Integrations',
    feat_snag: 'Snag List Feature',
    feat_drawings: 'Drawings Release to Site',
    feat_multilingual: 'Multi-lingual Support (English, Hindi & Telugu)',
    feat_secure: 'Secure Data Storage',
    sub_onetime: 'Single project access',
    sub_starter: 'Up to 5 projects',
    sub_pro: 'Up to 10 projects',
    sub_enterprise: 'Above 10 projects',
    validity_90: 'Valid for 90 days',
    free_trial_14: '14 Day Free Trial',
    buy_now: 'Buy Now',
    get_started: 'Get Started',
    upgrade_pro: 'Upgrade to Pro',
    contact_sales: 'Contact Sales',
  },
  hi: {
    welcome_back: 'वापसी पर स्वागत है',
    hi: 'नमस्ते',
    dashboard: 'डैशबोर्ड',
    upload: 'अपलोड',
    activity: 'गतिविधि',
    profile: 'प्रोफ़ाइल',
    snag_list: 'स्नैग सूची',
    user_mgmt: 'उपयोगकर्ता प्रबंधन',
    billing: 'प्लान/अपग्रेड',
    projects: 'परियोजनाएं',
    documents: 'दस्तावेज़',
    photos: 'तस्वीरें',
    sign_in: 'साइन इन',
    sign_up: 'साइन अप',
    sign_out: 'साइन आउट',
    settings: 'सेटिंग्स',
    analytics: 'एनालिटिक्स',
    notifications_label: 'सूचनाएं',
    chats: 'चैट्स',
    teams: 'टीम्स',
    org_users: 'संगठन उपयोगकर्ता',
    all_projects: 'सभी प्रोजेक्ट्स',
    organization_projects: 'संगठन प्रोजेक्ट्स',
    all_organizations: 'सभी संगठन',
    create_project: 'प्रोजेक्ट बनाएं',
    search: 'खोजें',
    notifications: 'सूचनाएं',
    help_support: 'सहायता और समर्थन',
    feedback: 'प्रतिक्रिया',
    your_projects: 'आपकी परियोजनाएं',
    total_projects: 'कुल परियोजनाएं',
    manage_projects: 'अपनी सभी कंपनी परियोजनाएं प्रबंधित करें',
    assigned_projects: 'अपनी सौंपी गई परियोजनाओं को देखें और योगदान दें',
    shared_projects: 'अपनी साझा परियोजना फ़ाइलें एक्सेस करें',
    no_projects: 'कोई परियोजना उपलब्ध नहीं',
    language: 'भाषा',
    english: 'अंग्रेज़ी',
    hindi: 'हिन्दी',
    telugu: 'తెలుగు',
    choose_plan: 'योजना चुनें',
    recommended: 'सुझाया गया',
    standard: 'स्टैंडर्ड',
    intermediate: 'इंटरमीडिएट',
    pro: 'प्रो',
    project_overview: 'परियोजना अवलोकन',
    back_to_projects: 'परियोजनाओं पर वापस जाएं',
    daily_reports: 'दैनिक रिपोर्ट',
    weekly_reports: 'साप्ताहिक रिपोर्ट',
    manuals: 'चेकलिस्ट',
    project_not_found: 'परियोजना नहीं मिली।',
    back_to_dashboard: 'डैशबोर्ड पर वापस जाएं',
    name_update_success: 'नाम सफलतापूर्वक अपडेट किया गया',
    name_update_error: 'नाम अपडेट करने में विफल',
    company_settings: 'कंपनी सेटिंग्स',
    company_name_label: 'कंपनी का नाम',
    company_name_placeholder: 'कंपनी का नाम दर्ज करें',
    company_name_success: 'कंपनी का नाम अपडेट किया गया',
    company_name_error: 'कंपनी का नाम अपडेट करने में विफल',
    company_logo_success: 'कंपनी का लोगो अपडेट किया गया',
    company_logo_error: 'कंपनी का लोगो अपलोड करने में विफल',
    tap_change_logo: 'लोगो बदलने के लिए टैप करें',
    change_password: 'पासवर्ड बदलें',
    current_password: 'वर्तमान पासवर्ड',
    new_password: 'नया पासवर्ड',
    confirm_password: 'नए पासवर्ड की पुष्टि करें',
    password_mismatch: 'पासवर्ड मेल नहीं खाते',
    password_success: 'पासवर्ड सफलतापूर्वक अपडेट किया गया',
    password_error: 'पासवर्ड अपडेट करने में विफल',
    update_password: 'पासवर्ड अपडेट करें',
    trash_management: 'ट्रैश प्रबंधन',
    trash_management_subtitle: 'हటాए गए प्रोजेक्ट्स को रिकवर या डिलीट करें',
    crop_photo_title: 'प्रोफ़ाइल फ़ोटो काटें',
    save_photo: 'फ़ोटो सहेजें',
    profile_pic_success: 'प्रोफ़ाइल चित्र सफलतापूर्वक अपडेट किया गया',
    profile_pic_error: 'प्रोफ़ाइल चित्र अपलोड करने में विफल',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    trash_title: 'ट्रैश',
    trash_subtitle: 'हटाए गए प्रोजेक्ट्स को प्रबंधित और पुनर्स्थापित करें',
    loading_trash: 'ट्रैश लोड हो रहा है...',
    trash_empty: 'ट्रैश खाली है',
    trash_empty_desc: 'हटाए गए प्रोजेक्ट स्थायी रूप से हटाए जाने से पहले 30 दिनों तक यहां दिखाई देंगे।',
    day_left: 'दिन शेष',
    days_left: 'दिन शेष',
    no_description: 'कोई विवरण उपलब्ध नहीं',
    deleted_at: 'हटाया गया',
    restore: 'पुनर्स्थापित करें',
    delete_forever: 'हमेशा के लिए हटा दें',
    restore_success: 'प्रोजेक्ट सफलतापूर्वक पुनर्स्थापित किया गया',
    restore_error: 'प्रोजेक्ट को पुनर्स्थापित करने में विफल',
    permanent_delete_success: 'प्रोजेक्ट स्थायी रूप से हटा दिया गया',
    permanent_delete_error: 'प्रोजेक्ट को हटाने में विफल',
    load_trash_error: 'ट्रैश लोड करने में विफल',
    permanent_delete_confirm: 'क्या आप वाकई ऐसा करना चाहते हैं? यह स्थायी रूप से सभी प्रोजेक्ट डेटा को हटा देगा। इसे पूर्ववत नहीं किया जा सकता।',
    no_permission: 'आपको इस पृष्ठ को देखने की अनुमति नहीं है।',
    load_users_error: 'उपयोगकर्ताओं को लोड करने में विफल',
    invalid_email: 'कृपया एक मान्य ईमेल दर्ज करें',
    select_project_role: 'कृपया इस भूमिका के लिए एक प्रोजेक्ट चुनें',
    invite_success: 'निमंत्रण सफलतापूर्वक भेजा गया',
    invite_error: 'निमंत्रण भेजने में विफल',
    remove_access_success: 'प्रोजेक्ट एक्सेस सफलतापूर्वक हटा दिया गया',
    remove_access_error: 'प्रोजेक्ट एक्सेस हटाने में विफल',
    link_copied: 'लिंक क्लिपबोर्ड पर कॉपी किया गया',
    user_mgmt_subtitle: 'संगठन के सदस्यों और भूमिकाओं को प्रबंधित करें।',
    add_member: 'सदस्य जोड़ें',
    email_address: 'ईमेल पता',
    role: 'भूमिका',
    assign_project: 'प्रोजेक्ट सौंपें',
    choose_project: 'प्रोजेक्ट चुनें',
    no_projects_found: 'कोई प्रोजेक्ट नहीं मिला',
    invite: 'आमंत्रित करें',
    project_access_links: 'प्रोजेक्ट एक्सेस लिंक',
    project_access_links_subtitle: 'आंतरिक योगदानकर्ताओं और बाहरी ग्राहकों के लिए सीधे लॉगिन लिंक जेनरेट करें।',
    select_project_placeholder: 'एक प्रोजेक्ट चुनें',
    contributor_access: 'योगदानकर्ता एक्सेस',
    client_access: 'ग्राहक एक्सेस',
    copy_link: 'लिंक कॉपी करें',
    copied: 'कॉपी किया गया',
    no_project_selected: 'कोई प्रोजेक्ट नहीं चुना गया',
    no_project_selected_subtitle: 'योगदानकर्ताओं और ग्राहकों के लिए सीधे एक्सेस लिंक जेनरेट करने के लिए कृपया ऊपर दिए गए ड्रॉपडाउन से एक प्रोजेक्ट चुनें।',
    member: 'सदस्य',
    status: 'स्थिति',
    joined: 'शामिल हुए',
    actions: 'कार्रवाई',
    invited_user: 'आमंत्रित उपयोगकर्ता',
    no_contact_info: 'कोई संपर्क जानकारी नहीं',
    all_projects_label: '(सभी प्रोजेक्ट्स)',
    no_projects_assigned: 'कोई प्रोजेक्ट नहीं सौंपा गया',
    verified: 'सत्यापित',
    pending: 'लंबित',
    no_users_found: 'आपके संगठन में कोई उपयोगकर्ता नहीं मिला।',
    remove_access_title: 'प्रोजेक्ट एक्सेस हटाएं?',
    remove_access_confirm: 'क्या आप वाकई {name} को उनके प्रोजेक्ट एक्सेस से हटाना चाहते हैं? उपयोगकर्ता खाता संगठन में रहेगा।',
    remove_access_button: 'एक्सेस हटाएं',
    admin: 'व्यवस्थापक',
    contributor: 'योगदानकर्ता',
    client: 'ग्राहक',
    // Billing
    billing_subtitle: 'अपनी टीम के लिए उपयुक्त योजना चुनें',
    monthly: 'मासिक',
    annual: 'वार्षिक',
    save_35: '35% बचाएं',
    plans_tab: 'योजनाएं',
    usage_tab: 'उपयोग',
    history_tab: 'इतिहास',
    most_popular: 'सबसे लोकप्रिय',
    billed_annually: 'सालाना बिल किया गया',
    incl_gst: '(18% जीएसटी सहित)',
    processing: 'प्रसंस्करण...',
    current_plan: 'वर्तमान योजना',
    resource_consumption: 'संसाधन खपत',
    resource_consumption_subtitle: 'आपके संगठन के संसाधन उपयोग का विस्तृत विवरण',
    plan_validity: 'योजना की वैधता',
    active_projects: 'सक्रिय परियोजनाएं',
    cloud_storage: 'क्लाउड स्टोरेज',
    team_members: 'टीम के सदस्य',
    clients: 'ग्राहक',
    snags: 'कमियां (Snags)',
    rfis: 'RFIs',
    active_status: 'सक्रिय',
    no_payment_history: 'कोई भुगतान इतिहास नहीं मिला।',
    invoice: 'इनवॉइस',
    cycle: 'चक्र',
    amount: 'राशि',
    date: 'तारीख',
    action: 'कार्रवाई',
    limit: 'सीमा',
    payment_success: 'भुगतान सफल! आपकी योजना अपग्रेड कर दी गई है।',
    payment_failed: 'भुगतान विफल',
    payment_error: 'भुगतान में कुछ गलत हो गया।',
    payment_sdk_error: 'रेजरपे SDK लोड करने में विफल रहा। कृपया अपना इंटरनेट कनेक्शन जांचें।',
    payment_verification_failed: 'भुगतान सत्यापन विफल रहा। कृपया सहायता से संपर्क करें।',
    price_custom: 'कस्टम',
    // Chats
    access_denied: 'पहुंच वर्जित',
    superadmin_chat_no_access: 'सुपरएडमिन के पास चैट सुविधा तक पहुंच नहीं है।',
    loading_chats: 'चैट लोड हो रही है...',
    search_chats: 'चैट खोजें...',
    no_chats_found: 'कोई चैट नहीं मिली',
    chat_fallback: 'चैट',
    more_projects: '+{count} और',
    user_is_typing: '{name} टाइप कर रहा है...',
    photo: 'फोटो',
    file: 'फाइल',
    group_chat: 'ग्रुप चैट',
    direct_message: 'डायरेक्ट मैसेज',
    loading_messages: 'संदेश लोड हो रहे हैं...',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    members_count: '{count} सदस्य',
    user_fallback: 'उपयोगकर्ता',
    voice_note: 'वॉयस नोट',
    photo_message: 'फोटो',
    file_message: 'फाइल',
    message_fallback: 'संदेश',
    replied_to_message: 'संदेश का उत्तर दिया',
    message_placeholder: 'संदेश लिखें...',
    new_group: 'नया ग्रुप',
    new_direct_chat: 'नई डायरेक्ट चैट',
    search_people: 'लोगों को खोजें...',
    group_name_placeholder: 'ग्रुप का नाम',
    users_selected: '{count} चयनित',
    create_group_btn: 'ग्रुप बनाएं ({count})',
    create_chat_btn: 'चैट बनाएं',
    enter_group_name: 'कृपया ग्रुप का नाम दर्ज करें',
    failed_create_chat: 'चैट बनाने में विफल',
    all_actions: 'सभी गतिविधियाँ',
    snags_label: 'कमियां (Snags)',
    rfi_label: 'RFI',
    members_label: 'सदस्य',
    back_to_unread: 'अपठित पर वापस जाएं',
    history: 'इतिहास',
    notifications_subtitle: 'परियोजना परिवर्तनों के साथ अपडेट रहें',
    mark_all_read: 'सभी को पढ़ा हुआ मानें',
    all_users: 'सभी उपयोगकर्ता',
    no_notifications_48h: 'पिछले 48 घंटों में कोई सूचना नहीं',
    no_new_notifications: 'कोई नई सूचना नहीं',
    all_caught_up: 'आप पूरी तरह से अपडेट हैं!',
    activity_subtitle: 'आपकी परियोजनाओं से अपडेट',
    no_recent_activity: 'कोई हालिया गतिविधि नहीं',
    // Features
    feat_single_proj: 'एकल परियोजना एक्सेस',
    feat_up_to_5: '5 परियोजनाओं तक',
    feat_up_to_10: '10 परियोजनाओं तक',
    feat_above_10: '10 से अधिक परियोजनाएं',
    feat_client_view: 'क्लाइंट व्यूअरशिप',
    feat_basic_report: 'बुनियादी रिपोर्टिंग',
    feat_struct_report: 'संरचित रिपोर्टिंग',
    feat_ai_report: 'AI-सहायता प्राप्त रिपोर्ट',
    feat_5gb: '5GB क्लाउड स्टोरेज',
    feat_25gb: '25GB क्लाउड स्टोरेज',
    feat_100gb: '100GB क्लाउड स्टोरेज',
    feat_above_100gb: '100GB से अधिक क्लाउड स्टोरेज',
    feat_onetime: 'एक बार की खरीद',
    feat_basic_dash: 'बुनियादी प्रोजेक्ट डैशबोर्ड',
    feat_role_access: 'भूमिका आधारित एक्सेस',
    feat_media_doc: 'मीडिया दस्तावेजीकरण',
    feat_priority_supp: 'प्राथमिकता सहायता',
    feat_custom_wf: 'कस्टम वर्कफ़्लो',
    feat_custom_onboard: 'कस्टम ऑनबोर्डिंग',
    feat_dedic_supp: 'समर्पित सहायता',
    feat_custom_integ: 'कस्टम एकीकरण',
    feat_snag: 'स्नैग लिस्ट फीचर',
    feat_drawings: 'साइट पर चित्र रिलीज',
    feat_multilingual: 'बहुभाषी सहायता (अंग्रेजी, हिंदी और तेलुगु)',
    feat_secure: 'सुरक्षित डेटा स्टोरेज',
    sub_onetime: 'एकल परियोजना एक्सेस',
    sub_starter: '5 परियोजनाओं तक',
    sub_pro: '10 परियोजनाओं तक',
    sub_enterprise: '10 से अधिक परियोजनाएं',
    validity_90: '90 दिनों के लिए मान्य',
    free_trial_14: '14 दिन का मुफ्त परीक्षण',
    buy_now: 'अभी खरीदें',
    get_started: 'शुरू करें',
    upgrade_pro: 'प्रो में अपग्रेड करें',
    contact_sales: 'बिक्री टीम से संपर्क करें',
  },
  te: {
    welcome_back: 'తిరిగి స్వాగతం',
    hi: 'హాయ్',
    dashboard: 'డ్యాష్‌బోర్డ్',
    upload: 'అప్‌లోడ్',
    activity: 'కార్యాచరణ',
    profile: 'ప్రొఫైల్',
    snag_list: 'స్నాగ్ జాబితా',
    user_mgmt: 'వినియోగదారు నిర్వహణ',
    billing: 'ప్లాన్/అప్‌గ్రేడ్',
    projects: 'ప్రాజెక్ట్‌లు',
    documents: 'పత్రాలు',
    photos: 'ఫోటోలు',
    sign_in: 'సైన్ ఇన్',
    sign_up: 'సైన్ అప్',
    sign_out: 'సైన్ అవుట్',
    settings: 'సెట్టింగ్‌లు',
    analytics: 'అనలిటిక్స్',
    notifications_label: 'నోటిఫికేషన్లు',
    chats: 'చాట్స్',
    teams: 'టీమ్స్',
    org_users: 'సంస్థ వినియోగదారులు',
    all_projects: 'అన్ని ప్రాజెక్ట్‌లు',
    organization_projects: 'సంస్థ ప్రాజెక్ట్‌లు',
    all_organizations: 'అన్ని సంస్థలు',
    create_project: 'ప్రాజెక్ట్ సృష్టించండి',
    search: 'వెతకండి',
    notifications: 'నోటిఫికేషన్లు',
    help_support: 'సహాయం & మద్దతు',
    feedback: 'అభిప్రాయం',
    your_projects: 'మీ ప్రాజెక్ట్‌లు',
    total_projects: 'మొత్తం ప్రాజెక్ట్‌లు',
    manage_projects: 'మీ అన్ని కంపెనీ ప్రాజెక్ట్‌లను నిర్వహించండి',
    assigned_projects: 'మీ కేటాయించిన ప్రాజెక్ట్‌లను చూడండి',
    shared_projects: 'మీ షేర్ చేసిన ప్రాజెక్ట్ ఫైల్‌లను యాక్సెస్ చేయండి',
    no_projects: 'ప్రాజెక్ట్‌లు అందుబాటులో లేవు',
    language: 'భాష',
    english: 'ఆంగ్లం',
    hindi: 'హిందీ',
    telugu: 'తెలుగు',
    choose_plan: 'ప్లాన్ ఎంచుకోండి',
    recommended: 'సిఫార్సు చేయబడింది',
    standard: 'స్టాండర్డ్',
    intermediate: 'ఇంటర్మీడియట్',
    pro: 'ప్రో',
    project_overview: 'ప్రాజెక్ట్ అవలోకనం',
    back_to_projects: 'ప్రాజెక్ట్‌లకు తిరిగి వెళ్ళు',
    daily_reports: 'రోజువారీ నివేదికలు',
    weekly_reports: 'వారపు నివేదికలు',
    manuals: 'చెక్‌లిస్ట్',
    project_not_found: 'ప్రాజెక్ట్ కనుగొనబడలేదు.',
    back_to_dashboard: 'డ్యాష్‌బోర్డ్‌కు తిరిగి వెళ్ళు',
    name_update_success: 'పేరు విజయవంతంగా నవీకరించబడింది',
    name_update_error: 'పేరును నవీకరించడంలో విఫలమైంది',
    company_settings: 'కంపెనీ సెట్టింగ్‌లు',
    company_name_label: 'కంపెనీ పేరు',
    company_name_placeholder: 'కంపెనీ పేరు నమోదు చేయండి',
    company_name_success: 'కంపెనీ పేరు నవీకరించబడింది',
    company_name_error: 'కంపెనీ పేరును నవీకరించడంలో విఫలమైంది',
    company_logo_success: 'కంపెనీ లోగో నవీకరించబడింది',
    company_logo_error: 'కంపెనీ లోగోను అప్‌లోడ్ చేయడంలో విఫలమైంది',
    tap_change_logo: 'లోగో మార్చడానికి నొక్కండి',
    change_password: 'పాస్‌వర్డ్ మార్చండి',
    current_password: 'ప్రస్తుత పాస్‌వర్డ్',
    new_password: 'కొత్త పాస్‌వర్డ్',
    confirm_password: 'కొత్త పాస్‌వర్డ్‌ను నిర్ధారించండి',
    password_mismatch: 'పాస్‌వర్డ్‌లు సరిపోలడం లేదు',
    password_success: 'పాస్‌వర్డ్ విజయవంతంగా నవీకరించబడింది',
    password_error: 'పాస్‌వర్డ్‌ను నవీకరించడంలో విఫలమైంది',
    update_password: 'పాస్‌వర్డ్ నవీకరించండి',
    trash_management: 'ట్రాష్ మేనేజ్‌మెంట్',
    trash_management_subtitle: 'తొలగించబడిన ప్రాజెక్ట్‌లను పునరుద్ధరించండి లేదా తొలగించండి',
    crop_photo_title: 'ప్రొఫైల్ ఫోటోను క్రాప్ చేయండి',
    save_photo: 'ఫోటోను సేవ్ చేయి',
    profile_pic_success: 'ప్రొఫైల్ చిత్రం విజయవంతంగా నవీకరించబడింది',
    profile_pic_error: 'ప్రొఫైల్ చిత్రాన్ని అప్‌లోడ్ చేయడంలో విఫలమైంది',
    cancel: 'రద్దు చేయి',
    save: 'సేవ్ చేయి',
    trash_title: 'ట్రాష్',
    trash_subtitle: 'తొలగించబడిన ప్రాజెక్ట్‌లను నిర్వహించండి మరియు పునరుద్ధరించండి',
    loading_trash: 'ట్రాష్ లోడ్ అవుతోంది...',
    trash_empty: 'ట్రాష్ ఖాళీగా ఉంది',
    trash_empty_desc: 'తొలగించబడిన ప్రాజెక్ట్‌లు శాశ్వతంగా తీసివేయబడకముందే 30 రోజుల పాటు ఇక్కడ కనిపిస్తాయి.',
    day_left: 'రోజు మిగిలి ఉంది',
    days_left: 'రోజులు మిగిలి ఉన్నాయి',
    no_description: 'వివరణ అందుబాటులో లేదు',
    deleted_at: 'తొలగించబడింది',
    restore: 'పునరుద్ధరించు',
    delete_forever: 'శాశ్వతంగా తొలగించు',
    restore_success: 'ప్రాజెక్ట్ విజయవంతంగా పునరుద్ధరించబడింది',
    restore_error: 'ప్రాజెక్ట్‌ను పునరుద్ధరించడంలో విఫలమైంది',
    permanent_delete_success: 'ప్రాజెక్ట్ శాశ్వతంగా తొలగించబడింది',
    permanent_delete_error: 'ప్రాజెక్ట్‌ను తొలగించడంలో విఫలమైంది',
    load_trash_error: 'ట్రాష్‌ను లోడ్ చేయడంలో విఫలమైంది',
    permanent_delete_confirm: 'మీకు ఖచ్చితంగా తెలుసా? ఇది మొత్తం ప్రాజెక్ట్ డేటాను శాశ్వతంగా తొలగిస్తుంది. ఇది వెనక్కి తీసుకోబడదు.',
    no_permission: 'ఈ పేజీని చూడటానికి మీకు అనుమతి లేదు.',
    load_users_error: 'వినియోగదారులను లోడ్ చేయడంలో విఫలమైంది',
    invalid_email: 'దయచేసి సరైన ఈమెయిల్ నమోదు చేయండి',
    select_project_role: 'దయచేసి ఈ పాత్ర కోసం ఒక ప్రాజెక్ట్‌ను ఎంచుకోండి',
    invite_success: 'ఆహ్వానం విజయవంతంగా పంపబడింది',
    invite_error: 'ఆహ్వానం పంపడంలో విఫలమైంది',
    remove_access_success: 'ప్రాజెక్ట్ యాక్సెస్ విజయవంతంగా తీసివేయబడింది',
    remove_access_error: 'ప్రాజెక్ట్ యాక్సెస్‌ను తీసివేయడంలో విఫలమైంది',
    link_copied: 'లింక్ క్లిప్‌బోర్డ్‌కు కాపీ చేయబడింది',
    user_mgmt_subtitle: 'సంస్థ సభ్యులు మరియు పాత్రలను నిర్వహించండి.',
    add_member: 'సభ్యుడిని జోడించు',
    email_address: 'ఈమెయిల్ చిరునామా',
    role: 'పాత్ర',
    assign_project: 'ప్రాజెక్ట్‌ను కేటాయించు',
    choose_project: 'ప్రాజెక్ట్‌ను ఎంచుకోండి',
    no_projects_found: 'ప్రాజెక్ట్‌లు ఏవీ కనుగొనబడలేదు',
    invite: 'ఆహ్వానించు',
    project_access_links: 'ప్రాజెక్ట్ యాక్సెస్ లింక్‌లు',
    project_access_links_subtitle: 'అంతర్గత సహకారులు మరియు బాహ్య క్లయింట్‌ల కోసం డైరెక్ట్ లాగిన్ లింక్‌లను రూపొందించండి.',
    select_project_placeholder: 'ఒక ప్రాజెక్ట్‌ను ఎంచుకోండి',
    contributor_access: 'సహకారి యాక్సెస్',
    client_access: 'క్లయింట్ యాక్సెస్',
    copy_link: 'లింక్ కాపీ చేయి',
    copied: 'కాపీ చేయబడింది',
    no_project_selected: 'ఏ ప్రాజెక్ట్ ఎంపిక కాలేదు',
    no_project_selected_subtitle: 'సహకారులు మరియు క్లయింట్‌ల కోసం నేరుగా యాక్సెస్ లింక్‌లను రూపొందించడానికి దయచేసి పైన ఉన్న డ్రాప్‌డౌన్ నుండి ప్రాజెక్ట్‌ను ఎంచుకోండి.',
    member: 'సభ్యుడు',
    status: 'స్థితి',
    joined: 'చేరారు',
    actions: 'చర్యలు',
    invited_user: 'ఆహ్వానించబడిన వినియోగదారు',
    no_contact_info: 'సంప్రదింపు సమాచారం లేదు',
    all_projects_label: '(అన్ని ప్రాజెక్ట్‌లు)',
    no_projects_assigned: 'ప్రాజెక్ట్‌లు ఏవీ కేటాయించబడలేదు',
    verified: 'ధృవీకరించబడింది',
    pending: 'పెండింగ్‌లో ఉంది',
    no_users_found: 'మీ సంస్థలో వినియోగదారులు ఎవరూ కనుగొనబడలేదు.',
    remove_access_title: 'ప్రొజెక్ట్ యాక్సెస్‌ను తీసివేయాలా?',
    remove_access_confirm: 'మీరు {name}ని వారి ప్రాజెక్ట్ యాక్సెస్ నుండి తీసివేయాలనుకుంటున్నారా? వినియోగదారు ఖాతా సంస్థలో ఉంటుంది.',
    remove_access_button: 'యాక్సెస్‌ను తీసివేయి',
    admin: 'నిర్వాహకుడు',
    contributor: 'సహకారి',
    client: 'క్లయింట్',
    // Billing
    billing_subtitle: 'మీ బృందానికి సరిపోయే ప్లాన్‌ను ఎంచుకోండి',
    monthly: 'నెలవారీ',
    annual: 'వార్షిక',
    save_35: '35% ఆదా చేయండి',
    plans_tab: 'ప్లాన్‌లు',
    usage_tab: 'వినియోగం',
    history_tab: 'చరిత్ర',
    most_popular: 'అత్యంత ప్రజాదరణ పొందినది',
    billed_annually: 'ఏడాదికి బిల్ చేయబడింది',
    incl_gst: '(18% GSTతో కలిపి)',
    processing: 'ప్రాసెసింగ్...',
    current_plan: 'ప్రస్తుత ప్లాన్',
    resource_consumption: 'వనరుల వినియోగం',
    resource_consumption_subtitle: 'మీ సంస్థ యొక్క వనరుల వినియోగం యొక్క వివరణాత్మక విభజన',
    plan_validity: 'ప్లాన్ ప్రామాణికత',
    active_projects: 'క్రియాశీల ప్రాజెక్ట్‌లు',
    cloud_storage: 'క్లౌడ్ స్టోరేజ్',
    team_members: 'బృందం సభ్యులు',
    clients: 'క్లయింట్లు',
    snags: 'స్నాగ్స్ (Snags)',
    rfis: 'RFIs',
    active_status: 'క్రియాశీల',
    no_payment_history: 'చెల్లింపు చరిత్ర ఏదీ కనుగొనబడలేదు.',
    invoice: 'ఇన్‌వాయిస్',
    cycle: 'చక్రం',
    amount: 'మొత్తం',
    date: 'తేదీ',
    action: 'చర్య',
    limit: 'పరిమితి',
    payment_success: 'చెల్లింపు విజయవంతమైంది! మీ ప్లాన్ అప్‌గ్రేడ్ చేయబడింది.',
    payment_failed: 'చెల్లింపు విఫలమైంది',
    payment_error: 'చెల్లింపులో ఏదో తప్పు జరిగింది.',
    payment_sdk_error: 'Razorpay SDK లోడ్ కావడంలో విఫలమైంది. దయచేసి మీ ఇంటర్నెట్ కనెక్షన్‌ని తనిఖీ చేయండి.',
    payment_verification_failed: 'చెల్లింపు ధృవీకరణ విఫలమైంది. దయచేసి మద్దతును సంప్రదించండి.',
    price_custom: 'కస్టమ్',
    // Chats
    access_denied: 'యాక్సెస్ తిరస్కరించబడింది',
    superadmin_chat_no_access: 'సూపర్ అడ్మిన్‌లకు చాట్ ఫీచర్‌కు యాక్సెస్ లేదు.',
    loading_chats: 'చాట్‌లు లోడ్ అవుతున్నాయి...',
    search_chats: 'చాట్‌లను వెతకండి...',
    no_chats_found: 'చాట్‌లు ఏవీ కనుగొనబడలేదు',
    chat_fallback: 'చాట్',
    more_projects: '+{count} మరిన్ని',
    user_is_typing: '{name} టైప్ చేస్తున్నారు...',
    photo: 'ఫోటో',
    file: 'ఫైల్',
    group_chat: 'గ్రూప్ చాట్',
    direct_message: 'డైరెక్ట్ మెసేజ్',
    loading_messages: 'సందేశాలు లోడ్ అవుతున్నాయి...',
    online: 'ఆన్‌లైన్',
    offline: 'ఆఫ్‌లైన్',
    members_count: '{count} సభ్యులు',
    user_fallback: 'వినియోగదారు',
    voice_note: 'వాయిస్ నోట్',
    photo_message: 'ఫోటో',
    file_message: 'ఫైల్',
    message_fallback: 'సందేశం',
    replied_to_message: 'సందేశానికి ప్రత్యుత్తరం ఇచ్చారు',
    message_placeholder: 'సందేశం...',
    new_group: 'కొత్త గ్రూప్',
    new_direct_chat: 'కొత్త డైరెక్ట్ చాట్',
    search_people: 'వ్యక్తులను వెతకండి...',
    group_name_placeholder: 'గ్రూప్ పేరు',
    users_selected: '{count} ఎంపిక చేయబడ్డారు',
    create_group_btn: 'గ్రూప్‌ను సృష్టించండి ({count})',
    create_chat_btn: 'చాట్‌ను సృష్టించండి',
    enter_group_name: 'దయచేసి గ్రూప్ పేరును నమోదు చేయండి',
    failed_create_chat: 'చాట్‌ను సృష్టించడంలో విఫలమైంది',
    all_actions: 'అన్ని చర్యలు',
    snags_label: 'స్నాగ్స్ (Snags)',
    rfi_label: 'RFI',
    members_label: 'సభ్యులు',
    back_to_unread: 'చదవని వాటికి తిరిగి వెళ్ళు',
    history: 'చరిత్ర',
    notifications_subtitle: 'ప్రాజెక్ట్ మార్పులతో అప్‌డేట్‌గా ఉండండి',
    mark_all_read: 'అన్నీ చదివినట్లుగా గుర్తించు',
    all_users: 'అన్ని వినియోగదారులు',
    no_notifications_48h: 'గత 48 గంటల్లో నోటిఫికేషన్లు ఏవీ లేవు',
    no_new_notifications: 'కొత్త నోటిఫికేషన్లు ఏవీ లేవు',
    all_caught_up: 'మీరు అంతా చూసేశారు!',
    activity_subtitle: 'మీ ప్రాజెక్ట్‌ల నుండి అప్‌డేట్‌లు',
    no_recent_activity: 'ఇటీవలి కార్యాచరణ ఏదీ లేదు',
    // Features
    feat_single_proj: 'సింగిల్ ప్రాజెక్ట్ యాక్సెస్',
    feat_up_to_5: '5 ప్రాజెక్ట్‌ల వరకు',
    feat_up_to_10: '10 ప్రాజెక్ట్‌ల వరకు',
    feat_above_10: '10 కంటే ఎక్కువ ప్రాజెక్ట్‌లు',
    feat_client_view: 'క్లయింట్ వీక్షించడం',
    feat_basic_report: 'ప్రాథమిక నివేదికలు',
    feat_struct_report: 'నిర్మాణాత్మక నివేదికలు',
    feat_ai_report: 'AI-సహాయక నివేదికలు',
    feat_5gb: '5GB క్లౌడ్ స్టోరేజ్',
    feat_25gb: '25GB క్లౌడ్ స్టోరేజ్',
    feat_100gb: '100GB క్లౌడ్ స్టోరేజ్',
    feat_above_100gb: '100GB కంటే ఎక్కువ క్లౌడ్ స్టోరేజ్',
    feat_onetime: 'ఒకసారి కొనుగోలు',
    feat_basic_dash: 'ప్రాథమిక ప్రాజెక్ట్ డాష్‌బోర్డ్',
    feat_role_access: 'పాత్ర-ఆధారిత యాక్సెస్',
    feat_media_doc: 'మీడియా డాక్యుమెంటేషన్',
    feat_priority_supp: 'ప్రాధాన్యత మద్దతు',
    feat_custom_wf: 'కస్టమ్ వర్క్‌ఫ్లోస్',
    feat_custom_onboard: 'కస్టమ్ ఆన్‌బోర్డింగ్',
    feat_dedic_supp: 'ప్రత్యేక మద్దతు',
    feat_custom_integ: 'కస్టమ్ ఇంటిగ్రేషన్స్',
    feat_snag: 'స్నాగ్ లిస్ట్ ఫీచర్',
    feat_drawings: 'సైట్‌కు డ్రాయింగ్ల విడుదల',
    feat_multilingual: 'బహుభాషా మద్దతు (ఇంగ్లీష్, హిందీ & తెలుగు)',
    feat_secure: 'సురక్షిత డేటా నిల్వ',
    sub_onetime: 'సింగిల్ ప్రాజెక్ట్ యాక్సెస్',
    sub_starter: '5 ప్రాజెక్ట్‌ల వరకు',
    sub_pro: '10 ప్రాజెక్ట్‌ల వరకు',
    sub_enterprise: '10 కంటే ఎక్కువ ప్రాజెక్ట్‌లు',
    validity_90: '90 రోజుల పాటు చెల్లుబాటు అవుతుంది',
    free_trial_14: '14 రోజుల ఉచిత ట్రయల్',
    buy_now: 'ఇప్పుడే కొనండి',
    get_started: 'ప్రారంభించండి',
    upgrade_pro: 'ప్రోకి అప్‌గ్రేడ్ చేయండి',
    contact_sales: 'సేల్స్ టీమ్‌ని సంప్రదించండి',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => { },
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      return (localStorage.getItem('apexis-lang') as Language) || 'en';
    }
    return 'en';
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('apexis-lang', lang);
  }, []);

  const t = useCallback((key: string) => {
    return translations[language][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
